/**
 * @file AnalyticsDevicePortClient.h
 * @brief AnalyticsDevicePortService client (header-only)
 * @note This file is auto-generated by wsdl_parser2, do not modify manually
 */

#pragma once

#include <libonvif_client/core/onvif_service_base.h>
#include <libonvif_client/core/onvif_callback.h>
#include <libonvif_client/types/tad.h>

namespace libonvif_client {

/**
 * @brief AnalyticsDevicePortService client
 * @namespace http://www.onvif.org/ver10/analyticsdevice/wsdl
 */
class AnalyticsDevicePortClient : public OnvifServiceBase {
public:
    /**
     * @brief Constructor
     * @param service_url ONVIF service endpoint URL
     * @param http_client HTTP client implementation (user provided)
     * @param username Authentication username (optional)
     * @param password Authentication password (optional)
     */
    AnalyticsDevicePortClient(const std::string& service_url,
                    const std::shared_ptr<IHttpClient>& http_client,
                    const std::string& username = "",
                    const std::string& password = "")
        : OnvifServiceBase(service_url, http_client, username, password) {
    }

    /**
     * @brief GetServiceCapabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetServiceCapabilities(const tad_GetServiceCapabilities& request,
                           const OnvifCallback<tad_GetServiceCapabilitiesResponse>& callback) {
        call_service<tad_GetServiceCapabilities, tad_GetServiceCapabilitiesResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetServiceCapabilities",
            request,
            "GetServiceCapabilities",
            "GetServiceCapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief DeleteAnalyticsEngineControl operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteAnalyticsEngineControl(const tad_DeleteAnalyticsEngineControl& request,
                           const OnvifCallback<tad_DeleteAnalyticsEngineControlResponse>& callback) {
        call_service<tad_DeleteAnalyticsEngineControl, tad_DeleteAnalyticsEngineControlResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/DeleteAnalyticsEngineControl",
            request,
            "DeleteAnalyticsEngineControl",
            "DeleteAnalyticsEngineControlResponse",
            callback
        );
    }

    /**
     * @brief CreateAnalyticsEngineControl operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateAnalyticsEngineControl(const tad_CreateAnalyticsEngineControl& request,
                           const OnvifCallback<tad_CreateAnalyticsEngineControlResponse>& callback) {
        call_service<tad_CreateAnalyticsEngineControl, tad_CreateAnalyticsEngineControlResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/CreateAnalyticsEngineControl",
            request,
            "CreateAnalyticsEngineControl",
            "CreateAnalyticsEngineControlResponse",
            callback
        );
    }

    /**
     * @brief SetAnalyticsEngineControl operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetAnalyticsEngineControl(const tad_SetAnalyticsEngineControl& request,
                           const OnvifCallback<tad_SetAnalyticsEngineControlResponse>& callback) {
        call_service<tad_SetAnalyticsEngineControl, tad_SetAnalyticsEngineControlResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/SetAnalyticsEngineControl",
            request,
            "SetAnalyticsEngineControl",
            "SetAnalyticsEngineControlResponse",
            callback
        );
    }

    /**
     * @brief GetAnalyticsEngineControl operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAnalyticsEngineControl(const tad_GetAnalyticsEngineControl& request,
                           const OnvifCallback<tad_GetAnalyticsEngineControlResponse>& callback) {
        call_service<tad_GetAnalyticsEngineControl, tad_GetAnalyticsEngineControlResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsEngineControl",
            request,
            "GetAnalyticsEngineControl",
            "GetAnalyticsEngineControlResponse",
            callback
        );
    }

    /**
     * @brief GetAnalyticsEngineControls operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAnalyticsEngineControls(const tad_GetAnalyticsEngineControls& request,
                           const OnvifCallback<tad_GetAnalyticsEngineControlsResponse>& callback) {
        call_service<tad_GetAnalyticsEngineControls, tad_GetAnalyticsEngineControlsResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsEngineControls",
            request,
            "GetAnalyticsEngineControls",
            "GetAnalyticsEngineControlsResponse",
            callback
        );
    }

    /**
     * @brief GetAnalyticsEngine operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAnalyticsEngine(const tad_GetAnalyticsEngine& request,
                           const OnvifCallback<tad_GetAnalyticsEngineResponse>& callback) {
        call_service<tad_GetAnalyticsEngine, tad_GetAnalyticsEngineResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsEngine",
            request,
            "GetAnalyticsEngine",
            "GetAnalyticsEngineResponse",
            callback
        );
    }

    /**
     * @brief GetAnalyticsEngines operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAnalyticsEngines(const tad_GetAnalyticsEngines& request,
                           const OnvifCallback<tad_GetAnalyticsEnginesResponse>& callback) {
        call_service<tad_GetAnalyticsEngines, tad_GetAnalyticsEnginesResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsEngines",
            request,
            "GetAnalyticsEngines",
            "GetAnalyticsEnginesResponse",
            callback
        );
    }

    /**
     * @brief SetVideoAnalyticsConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetVideoAnalyticsConfiguration(const tad_SetVideoAnalyticsConfiguration& request,
                           const OnvifCallback<tad_SetVideoAnalyticsConfigurationResponse>& callback) {
        call_service<tad_SetVideoAnalyticsConfiguration, tad_SetVideoAnalyticsConfigurationResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/SetVideoAnalyticsConfiguration",
            request,
            "SetVideoAnalyticsConfiguration",
            "SetVideoAnalyticsConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetAnalyticsEngineInput operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetAnalyticsEngineInput(const tad_SetAnalyticsEngineInput& request,
                           const OnvifCallback<tad_SetAnalyticsEngineInputResponse>& callback) {
        call_service<tad_SetAnalyticsEngineInput, tad_SetAnalyticsEngineInputResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/SetAnalyticsEngineInput",
            request,
            "SetAnalyticsEngineInput",
            "SetAnalyticsEngineInputResponse",
            callback
        );
    }

    /**
     * @brief GetAnalyticsEngineInput operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAnalyticsEngineInput(const tad_GetAnalyticsEngineInput& request,
                           const OnvifCallback<tad_GetAnalyticsEngineInputResponse>& callback) {
        call_service<tad_GetAnalyticsEngineInput, tad_GetAnalyticsEngineInputResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsEngineInput",
            request,
            "GetAnalyticsEngineInput",
            "GetAnalyticsEngineInputResponse",
            callback
        );
    }

    /**
     * @brief GetAnalyticsEngineInputs operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAnalyticsEngineInputs(const tad_GetAnalyticsEngineInputs& request,
                           const OnvifCallback<tad_GetAnalyticsEngineInputsResponse>& callback) {
        call_service<tad_GetAnalyticsEngineInputs, tad_GetAnalyticsEngineInputsResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsEngineInputs",
            request,
            "GetAnalyticsEngineInputs",
            "GetAnalyticsEngineInputsResponse",
            callback
        );
    }

    /**
     * @brief GetAnalyticsDeviceStreamUri operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAnalyticsDeviceStreamUri(const tad_GetAnalyticsDeviceStreamUri& request,
                           const OnvifCallback<tad_GetAnalyticsDeviceStreamUriResponse>& callback) {
        call_service<tad_GetAnalyticsDeviceStreamUri, tad_GetAnalyticsDeviceStreamUriResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsDeviceStreamUri",
            request,
            "GetAnalyticsDeviceStreamUri",
            "GetAnalyticsDeviceStreamUriResponse",
            callback
        );
    }

    /**
     * @brief GetVideoAnalyticsConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoAnalyticsConfiguration(const tad_GetVideoAnalyticsConfiguration& request,
                           const OnvifCallback<tad_GetVideoAnalyticsConfigurationResponse>& callback) {
        call_service<tad_GetVideoAnalyticsConfiguration, tad_GetVideoAnalyticsConfigurationResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetVideoAnalyticsConfiguration",
            request,
            "GetVideoAnalyticsConfiguration",
            "GetVideoAnalyticsConfigurationResponse",
            callback
        );
    }

    /**
     * @brief CreateAnalyticsEngineInputs operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateAnalyticsEngineInputs(const tad_CreateAnalyticsEngineInputs& request,
                           const OnvifCallback<tad_CreateAnalyticsEngineInputsResponse>& callback) {
        call_service<tad_CreateAnalyticsEngineInputs, tad_CreateAnalyticsEngineInputsResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/CreateAnalyticsEngineInputs",
            request,
            "CreateAnalyticsEngineInputs",
            "CreateAnalyticsEngineInputsResponse",
            callback
        );
    }

    /**
     * @brief DeleteAnalyticsEngineInputs operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteAnalyticsEngineInputs(const tad_DeleteAnalyticsEngineInputs& request,
                           const OnvifCallback<tad_DeleteAnalyticsEngineInputsResponse>& callback) {
        call_service<tad_DeleteAnalyticsEngineInputs, tad_DeleteAnalyticsEngineInputsResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/DeleteAnalyticsEngineInputs",
            request,
            "DeleteAnalyticsEngineInputs",
            "DeleteAnalyticsEngineInputsResponse",
            callback
        );
    }

    /**
     * @brief GetAnalyticsState operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAnalyticsState(const tad_GetAnalyticsState& request,
                           const OnvifCallback<tad_GetAnalyticsStateResponse>& callback) {
        call_service<tad_GetAnalyticsState, tad_GetAnalyticsStateResponse>(
            "http://www.onvif.org/ver10/analyticsdevice/wsdl/GetAnalyticsState",
            request,
            "GetAnalyticsState",
            "GetAnalyticsStateResponse",
            callback
        );
    }

    const char *get_namespace_prefix() const override {
        return TARGET_NAMESPACE_PREFIX;
    }

    const char *get_namespace_uri() const override {
        return TARGET_NAMESPACE;
    }

    static constexpr const char* TARGET_NAMESPACE = "http://www.onvif.org/ver10/analyticsdevice/wsdl";
    static constexpr const char* TARGET_NAMESPACE_PREFIX = "tad";
};

} // namespace libonvif_client
