/**
 * @file DeviceClient.h
 * @brief DeviceService client (header-only)
 * @note This file is auto-generated by wsdl_parser2, do not modify manually
 */

#pragma once

#include <libonvif_client/core/onvif_service_base.h>
#include <libonvif_client/core/onvif_callback.h>
#include <libonvif_client/types/tds.h>

namespace libonvif_client {

/**
 * @brief DeviceService client
 * @namespace http://www.onvif.org/ver10/device/wsdl
 */
class DeviceClient : public OnvifServiceBase {
public:
    /**
     * @brief Constructor
     * @param service_url ONVIF service endpoint URL
     * @param http_client HTTP client implementation (user provided)
     * @param username Authentication username (optional)
     * @param password Authentication password (optional)
     */
    DeviceClient(const std::string& service_url,
                    const std::shared_ptr<IHttpClient>& http_client,
                    const std::string& username = "",
                    const std::string& password = "")
        : OnvifServiceBase(service_url, http_client, username, password) {
    }

    /**
     * @brief GetServices operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetServices(const tds_GetServices& request,
                           const OnvifCallback<tds_GetServicesResponse>& callback) {
        call_service<tds_GetServices, tds_GetServicesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetServices",
            request,
            "GetServices",
            "GetServicesResponse",
            callback
        );
    }

    /**
     * @brief GetServiceCapabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetServiceCapabilities(const tds_GetServiceCapabilities& request,
                           const OnvifCallback<tds_GetServiceCapabilitiesResponse>& callback) {
        call_service<tds_GetServiceCapabilities, tds_GetServiceCapabilitiesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetServiceCapabilities",
            request,
            "GetServiceCapabilities",
            "GetServiceCapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief GetDeviceInformation operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetDeviceInformation(const tds_GetDeviceInformation& request,
                           const OnvifCallback<tds_GetDeviceInformationResponse>& callback) {
        call_service<tds_GetDeviceInformation, tds_GetDeviceInformationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetDeviceInformation",
            request,
            "GetDeviceInformation",
            "GetDeviceInformationResponse",
            callback
        );
    }

    /**
     * @brief SetSystemDateAndTime operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetSystemDateAndTime(const tds_SetSystemDateAndTime& request,
                           const OnvifCallback<tds_SetSystemDateAndTimeResponse>& callback) {
        call_service<tds_SetSystemDateAndTime, tds_SetSystemDateAndTimeResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetSystemDateAndTime",
            request,
            "SetSystemDateAndTime",
            "SetSystemDateAndTimeResponse",
            callback
        );
    }

    /**
     * @brief GetSystemDateAndTime operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetSystemDateAndTime(const tds_GetSystemDateAndTime& request,
                           const OnvifCallback<tds_GetSystemDateAndTimeResponse>& callback) {
        call_service<tds_GetSystemDateAndTime, tds_GetSystemDateAndTimeResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetSystemDateAndTime",
            request,
            "GetSystemDateAndTime",
            "GetSystemDateAndTimeResponse",
            callback
        );
    }

    /**
     * @brief SetSystemFactoryDefault operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetSystemFactoryDefault(const tds_SetSystemFactoryDefault& request,
                           const OnvifCallback<tds_SetSystemFactoryDefaultResponse>& callback) {
        call_service<tds_SetSystemFactoryDefault, tds_SetSystemFactoryDefaultResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetSystemFactoryDefault",
            request,
            "SetSystemFactoryDefault",
            "SetSystemFactoryDefaultResponse",
            callback
        );
    }

    /**
     * @brief UpgradeSystemFirmware operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void UpgradeSystemFirmware(const tds_UpgradeSystemFirmware& request,
                           const OnvifCallback<tds_UpgradeSystemFirmwareResponse>& callback) {
        call_service<tds_UpgradeSystemFirmware, tds_UpgradeSystemFirmwareResponse>(
            "http://www.onvif.org/ver10/device/wsdl/UpgradeSystemFirmware",
            request,
            "UpgradeSystemFirmware",
            "UpgradeSystemFirmwareResponse",
            callback
        );
    }

    /**
     * @brief SystemReboot operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SystemReboot(const tds_SystemReboot& request,
                           const OnvifCallback<tds_SystemRebootResponse>& callback) {
        call_service<tds_SystemReboot, tds_SystemRebootResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SystemReboot",
            request,
            "SystemReboot",
            "SystemRebootResponse",
            callback
        );
    }

    /**
     * @brief RestoreSystem operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RestoreSystem(const tds_RestoreSystem& request,
                           const OnvifCallback<tds_RestoreSystemResponse>& callback) {
        call_service<tds_RestoreSystem, tds_RestoreSystemResponse>(
            "http://www.onvif.org/ver10/device/wsdl/RestoreSystem",
            request,
            "RestoreSystem",
            "RestoreSystemResponse",
            callback
        );
    }

    /**
     * @brief GetSystemBackup operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetSystemBackup(const tds_GetSystemBackup& request,
                           const OnvifCallback<tds_GetSystemBackupResponse>& callback) {
        call_service<tds_GetSystemBackup, tds_GetSystemBackupResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetSystemBackup",
            request,
            "GetSystemBackup",
            "GetSystemBackupResponse",
            callback
        );
    }

    /**
     * @brief GetSystemLog operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetSystemLog(const tds_GetSystemLog& request,
                           const OnvifCallback<tds_GetSystemLogResponse>& callback) {
        call_service<tds_GetSystemLog, tds_GetSystemLogResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetSystemLog",
            request,
            "GetSystemLog",
            "GetSystemLogResponse",
            callback
        );
    }

    /**
     * @brief GetSystemSupportInformation operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetSystemSupportInformation(const tds_GetSystemSupportInformation& request,
                           const OnvifCallback<tds_GetSystemSupportInformationResponse>& callback) {
        call_service<tds_GetSystemSupportInformation, tds_GetSystemSupportInformationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetSystemSupportInformation",
            request,
            "GetSystemSupportInformation",
            "GetSystemSupportInformationResponse",
            callback
        );
    }

    /**
     * @brief GetScopes operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetScopes(const tds_GetScopes& request,
                           const OnvifCallback<tds_GetScopesResponse>& callback) {
        call_service<tds_GetScopes, tds_GetScopesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetScopes",
            request,
            "GetScopes",
            "GetScopesResponse",
            callback
        );
    }

    /**
     * @brief SetScopes operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetScopes(const tds_SetScopes& request,
                           const OnvifCallback<tds_SetScopesResponse>& callback) {
        call_service<tds_SetScopes, tds_SetScopesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetScopes",
            request,
            "SetScopes",
            "SetScopesResponse",
            callback
        );
    }

    /**
     * @brief AddScopes operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddScopes(const tds_AddScopes& request,
                           const OnvifCallback<tds_AddScopesResponse>& callback) {
        call_service<tds_AddScopes, tds_AddScopesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/AddScopes",
            request,
            "AddScopes",
            "AddScopesResponse",
            callback
        );
    }

    /**
     * @brief RemoveScopes operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemoveScopes(const tds_RemoveScopes& request,
                           const OnvifCallback<tds_RemoveScopesResponse>& callback) {
        call_service<tds_RemoveScopes, tds_RemoveScopesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/RemoveScopes",
            request,
            "RemoveScopes",
            "RemoveScopesResponse",
            callback
        );
    }

    /**
     * @brief GetDiscoveryMode operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetDiscoveryMode(const tds_GetDiscoveryMode& request,
                           const OnvifCallback<tds_GetDiscoveryModeResponse>& callback) {
        call_service<tds_GetDiscoveryMode, tds_GetDiscoveryModeResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetDiscoveryMode",
            request,
            "GetDiscoveryMode",
            "GetDiscoveryModeResponse",
            callback
        );
    }

    /**
     * @brief SetDiscoveryMode operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetDiscoveryMode(const tds_SetDiscoveryMode& request,
                           const OnvifCallback<tds_SetDiscoveryModeResponse>& callback) {
        call_service<tds_SetDiscoveryMode, tds_SetDiscoveryModeResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetDiscoveryMode",
            request,
            "SetDiscoveryMode",
            "SetDiscoveryModeResponse",
            callback
        );
    }

    /**
     * @brief GetRemoteDiscoveryMode operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRemoteDiscoveryMode(const tds_GetRemoteDiscoveryMode& request,
                           const OnvifCallback<tds_GetRemoteDiscoveryModeResponse>& callback) {
        call_service<tds_GetRemoteDiscoveryMode, tds_GetRemoteDiscoveryModeResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetRemoteDiscoveryMode",
            request,
            "GetRemoteDiscoveryMode",
            "GetRemoteDiscoveryModeResponse",
            callback
        );
    }

    /**
     * @brief SetRemoteDiscoveryMode operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetRemoteDiscoveryMode(const tds_SetRemoteDiscoveryMode& request,
                           const OnvifCallback<tds_SetRemoteDiscoveryModeResponse>& callback) {
        call_service<tds_SetRemoteDiscoveryMode, tds_SetRemoteDiscoveryModeResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetRemoteDiscoveryMode",
            request,
            "SetRemoteDiscoveryMode",
            "SetRemoteDiscoveryModeResponse",
            callback
        );
    }

    /**
     * @brief GetDPAddresses operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetDPAddresses(const tds_GetDPAddresses& request,
                           const OnvifCallback<tds_GetDPAddressesResponse>& callback) {
        call_service<tds_GetDPAddresses, tds_GetDPAddressesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetDPAddresses",
            request,
            "GetDPAddresses",
            "GetDPAddressesResponse",
            callback
        );
    }

    /**
     * @brief SetDPAddresses operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetDPAddresses(const tds_SetDPAddresses& request,
                           const OnvifCallback<tds_SetDPAddressesResponse>& callback) {
        call_service<tds_SetDPAddresses, tds_SetDPAddressesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetDPAddresses",
            request,
            "SetDPAddresses",
            "SetDPAddressesResponse",
            callback
        );
    }

    /**
     * @brief GetEndpointReference operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetEndpointReference(const tds_GetEndpointReference& request,
                           const OnvifCallback<tds_GetEndpointReferenceResponse>& callback) {
        call_service<tds_GetEndpointReference, tds_GetEndpointReferenceResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetEndpointReference",
            request,
            "GetEndpointReference",
            "GetEndpointReferenceResponse",
            callback
        );
    }

    /**
     * @brief GetUserRoles operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetUserRoles(const tds_GetUserRoles& request,
                           const OnvifCallback<tds_GetUserRolesResponse>& callback) {
        call_service<tds_GetUserRoles, tds_GetUserRolesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetUserRoles",
            request,
            "GetUserRoles",
            "GetUserRolesResponse",
            callback
        );
    }

    /**
     * @brief SetUserRole operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetUserRole(const tds_SetUserRole& request,
                           const OnvifCallback<tds_SetUserRoleResponse>& callback) {
        call_service<tds_SetUserRole, tds_SetUserRoleResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetUserRole",
            request,
            "SetUserRole",
            "SetUserRoleResponse",
            callback
        );
    }

    /**
     * @brief DeleteUserRole operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteUserRole(const tds_DeleteUserRole& request,
                           const OnvifCallback<tds_DeleteUserRoleResponse>& callback) {
        call_service<tds_DeleteUserRole, tds_DeleteUserRoleResponse>(
            "http://www.onvif.org/ver10/device/wsdl/DeleteUserRole",
            request,
            "DeleteUserRole",
            "DeleteUserRoleResponse",
            callback
        );
    }

    /**
     * @brief GetRemoteUser operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRemoteUser(const tds_GetRemoteUser& request,
                           const OnvifCallback<tds_GetRemoteUserResponse>& callback) {
        call_service<tds_GetRemoteUser, tds_GetRemoteUserResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetRemoteUser",
            request,
            "GetRemoteUser",
            "GetRemoteUserResponse",
            callback
        );
    }

    /**
     * @brief SetRemoteUser operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetRemoteUser(const tds_SetRemoteUser& request,
                           const OnvifCallback<tds_SetRemoteUserResponse>& callback) {
        call_service<tds_SetRemoteUser, tds_SetRemoteUserResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetRemoteUser",
            request,
            "SetRemoteUser",
            "SetRemoteUserResponse",
            callback
        );
    }

    /**
     * @brief GetUsers operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetUsers(const tds_GetUsers& request,
                           const OnvifCallback<tds_GetUsersResponse>& callback) {
        call_service<tds_GetUsers, tds_GetUsersResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetUsers",
            request,
            "GetUsers",
            "GetUsersResponse",
            callback
        );
    }

    /**
     * @brief CreateUsers operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateUsers(const tds_CreateUsers& request,
                           const OnvifCallback<tds_CreateUsersResponse>& callback) {
        call_service<tds_CreateUsers, tds_CreateUsersResponse>(
            "http://www.onvif.org/ver10/device/wsdl/CreateUsers",
            request,
            "CreateUsers",
            "CreateUsersResponse",
            callback
        );
    }

    /**
     * @brief DeleteUsers operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteUsers(const tds_DeleteUsers& request,
                           const OnvifCallback<tds_DeleteUsersResponse>& callback) {
        call_service<tds_DeleteUsers, tds_DeleteUsersResponse>(
            "http://www.onvif.org/ver10/device/wsdl/DeleteUsers",
            request,
            "DeleteUsers",
            "DeleteUsersResponse",
            callback
        );
    }

    /**
     * @brief SetUser operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetUser(const tds_SetUser& request,
                           const OnvifCallback<tds_SetUserResponse>& callback) {
        call_service<tds_SetUser, tds_SetUserResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetUser",
            request,
            "SetUser",
            "SetUserResponse",
            callback
        );
    }

    /**
     * @brief GetWsdlUrl operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetWsdlUrl(const tds_GetWsdlUrl& request,
                           const OnvifCallback<tds_GetWsdlUrlResponse>& callback) {
        call_service<tds_GetWsdlUrl, tds_GetWsdlUrlResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetWsdlUrl",
            request,
            "GetWsdlUrl",
            "GetWsdlUrlResponse",
            callback
        );
    }

    /**
     * @brief GetPasswordComplexityOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetPasswordComplexityOptions(const tds_GetPasswordComplexityOptions& request,
                           const OnvifCallback<tds_GetPasswordComplexityOptionsResponse>& callback) {
        call_service<tds_GetPasswordComplexityOptions, tds_GetPasswordComplexityOptionsResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetPasswordComplexityOptions",
            request,
            "GetPasswordComplexityOptions",
            "GetPasswordComplexityOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetPasswordComplexityConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetPasswordComplexityConfiguration(const tds_GetPasswordComplexityConfiguration& request,
                           const OnvifCallback<tds_GetPasswordComplexityConfigurationResponse>& callback) {
        call_service<tds_GetPasswordComplexityConfiguration, tds_GetPasswordComplexityConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetPasswordComplexityConfiguration",
            request,
            "GetPasswordComplexityConfiguration",
            "GetPasswordComplexityConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetPasswordComplexityConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetPasswordComplexityConfiguration(const tds_SetPasswordComplexityConfiguration& request,
                           const OnvifCallback<tds_SetPasswordComplexityConfigurationResponse>& callback) {
        call_service<tds_SetPasswordComplexityConfiguration, tds_SetPasswordComplexityConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetPasswordComplexityConfiguration",
            request,
            "SetPasswordComplexityConfiguration",
            "SetPasswordComplexityConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetPasswordHistoryConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetPasswordHistoryConfiguration(const tds_GetPasswordHistoryConfiguration& request,
                           const OnvifCallback<tds_GetPasswordHistoryConfigurationResponse>& callback) {
        call_service<tds_GetPasswordHistoryConfiguration, tds_GetPasswordHistoryConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetPasswordHistoryConfiguration",
            request,
            "GetPasswordHistoryConfiguration",
            "GetPasswordHistoryConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetPasswordHistoryConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetPasswordHistoryConfiguration(const tds_SetPasswordHistoryConfiguration& request,
                           const OnvifCallback<tds_SetPasswordHistoryConfigurationResponse>& callback) {
        call_service<tds_SetPasswordHistoryConfiguration, tds_SetPasswordHistoryConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetPasswordHistoryConfiguration",
            request,
            "SetPasswordHistoryConfiguration",
            "SetPasswordHistoryConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetAuthFailureWarningOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAuthFailureWarningOptions(const tds_GetAuthFailureWarningOptions& request,
                           const OnvifCallback<tds_GetAuthFailureWarningOptionsResponse>& callback) {
        call_service<tds_GetAuthFailureWarningOptions, tds_GetAuthFailureWarningOptionsResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetAuthFailureWarningOptions",
            request,
            "GetAuthFailureWarningOptions",
            "GetAuthFailureWarningOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetAuthFailureWarningConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAuthFailureWarningConfiguration(const tds_GetAuthFailureWarningConfiguration& request,
                           const OnvifCallback<tds_GetAuthFailureWarningConfigurationResponse>& callback) {
        call_service<tds_GetAuthFailureWarningConfiguration, tds_GetAuthFailureWarningConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetAuthFailureWarningConfiguration",
            request,
            "GetAuthFailureWarningConfiguration",
            "GetAuthFailureWarningConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetAuthFailureWarningConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetAuthFailureWarningConfiguration(const tds_SetAuthFailureWarningConfiguration& request,
                           const OnvifCallback<tds_SetAuthFailureWarningConfigurationResponse>& callback) {
        call_service<tds_SetAuthFailureWarningConfiguration, tds_SetAuthFailureWarningConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetAuthFailureWarningConfiguration",
            request,
            "SetAuthFailureWarningConfiguration",
            "SetAuthFailureWarningConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetCapabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCapabilities(const tds_GetCapabilities& request,
                           const OnvifCallback<tds_GetCapabilitiesResponse>& callback) {
        call_service<tds_GetCapabilities, tds_GetCapabilitiesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetCapabilities",
            request,
            "GetCapabilities",
            "GetCapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief GetHostname operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetHostname(const tds_GetHostname& request,
                           const OnvifCallback<tds_GetHostnameResponse>& callback) {
        call_service<tds_GetHostname, tds_GetHostnameResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetHostname",
            request,
            "GetHostname",
            "GetHostnameResponse",
            callback
        );
    }

    /**
     * @brief SetHostname operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetHostname(const tds_SetHostname& request,
                           const OnvifCallback<tds_SetHostnameResponse>& callback) {
        call_service<tds_SetHostname, tds_SetHostnameResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetHostname",
            request,
            "SetHostname",
            "SetHostnameResponse",
            callback
        );
    }

    /**
     * @brief SetHostnameFromDHCP operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetHostnameFromDHCP(const tds_SetHostnameFromDHCP& request,
                           const OnvifCallback<tds_SetHostnameFromDHCPResponse>& callback) {
        call_service<tds_SetHostnameFromDHCP, tds_SetHostnameFromDHCPResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetHostnameFromDHCP",
            request,
            "SetHostnameFromDHCP",
            "SetHostnameFromDHCPResponse",
            callback
        );
    }

    /**
     * @brief GetDNS operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetDNS(const tds_GetDNS& request,
                           const OnvifCallback<tds_GetDNSResponse>& callback) {
        call_service<tds_GetDNS, tds_GetDNSResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetDNS",
            request,
            "GetDNS",
            "GetDNSResponse",
            callback
        );
    }

    /**
     * @brief SetDNS operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetDNS(const tds_SetDNS& request,
                           const OnvifCallback<tds_SetDNSResponse>& callback) {
        call_service<tds_SetDNS, tds_SetDNSResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetDNS",
            request,
            "SetDNS",
            "SetDNSResponse",
            callback
        );
    }

    /**
     * @brief GetNTP operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetNTP(const tds_GetNTP& request,
                           const OnvifCallback<tds_GetNTPResponse>& callback) {
        call_service<tds_GetNTP, tds_GetNTPResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetNTP",
            request,
            "GetNTP",
            "GetNTPResponse",
            callback
        );
    }

    /**
     * @brief SetNTP operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetNTP(const tds_SetNTP& request,
                           const OnvifCallback<tds_SetNTPResponse>& callback) {
        call_service<tds_SetNTP, tds_SetNTPResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetNTP",
            request,
            "SetNTP",
            "SetNTPResponse",
            callback
        );
    }

    /**
     * @brief GetDynamicDNS operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetDynamicDNS(const tds_GetDynamicDNS& request,
                           const OnvifCallback<tds_GetDynamicDNSResponse>& callback) {
        call_service<tds_GetDynamicDNS, tds_GetDynamicDNSResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetDynamicDNS",
            request,
            "GetDynamicDNS",
            "GetDynamicDNSResponse",
            callback
        );
    }

    /**
     * @brief SetDynamicDNS operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetDynamicDNS(const tds_SetDynamicDNS& request,
                           const OnvifCallback<tds_SetDynamicDNSResponse>& callback) {
        call_service<tds_SetDynamicDNS, tds_SetDynamicDNSResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetDynamicDNS",
            request,
            "SetDynamicDNS",
            "SetDynamicDNSResponse",
            callback
        );
    }

    /**
     * @brief GetNetworkInterfaces operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetNetworkInterfaces(const tds_GetNetworkInterfaces& request,
                           const OnvifCallback<tds_GetNetworkInterfacesResponse>& callback) {
        call_service<tds_GetNetworkInterfaces, tds_GetNetworkInterfacesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetNetworkInterfaces",
            request,
            "GetNetworkInterfaces",
            "GetNetworkInterfacesResponse",
            callback
        );
    }

    /**
     * @brief SetNetworkInterfaces operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetNetworkInterfaces(const tds_SetNetworkInterfaces& request,
                           const OnvifCallback<tds_SetNetworkInterfacesResponse>& callback) {
        call_service<tds_SetNetworkInterfaces, tds_SetNetworkInterfacesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetNetworkInterfaces",
            request,
            "SetNetworkInterfaces",
            "SetNetworkInterfacesResponse",
            callback
        );
    }

    /**
     * @brief GetNetworkProtocols operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetNetworkProtocols(const tds_GetNetworkProtocols& request,
                           const OnvifCallback<tds_GetNetworkProtocolsResponse>& callback) {
        call_service<tds_GetNetworkProtocols, tds_GetNetworkProtocolsResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetNetworkProtocols",
            request,
            "GetNetworkProtocols",
            "GetNetworkProtocolsResponse",
            callback
        );
    }

    /**
     * @brief SetNetworkProtocols operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetNetworkProtocols(const tds_SetNetworkProtocols& request,
                           const OnvifCallback<tds_SetNetworkProtocolsResponse>& callback) {
        call_service<tds_SetNetworkProtocols, tds_SetNetworkProtocolsResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetNetworkProtocols",
            request,
            "SetNetworkProtocols",
            "SetNetworkProtocolsResponse",
            callback
        );
    }

    /**
     * @brief GetNetworkDefaultGateway operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetNetworkDefaultGateway(const tds_GetNetworkDefaultGateway& request,
                           const OnvifCallback<tds_GetNetworkDefaultGatewayResponse>& callback) {
        call_service<tds_GetNetworkDefaultGateway, tds_GetNetworkDefaultGatewayResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetNetworkDefaultGateway",
            request,
            "GetNetworkDefaultGateway",
            "GetNetworkDefaultGatewayResponse",
            callback
        );
    }

    /**
     * @brief SetNetworkDefaultGateway operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetNetworkDefaultGateway(const tds_SetNetworkDefaultGateway& request,
                           const OnvifCallback<tds_SetNetworkDefaultGatewayResponse>& callback) {
        call_service<tds_SetNetworkDefaultGateway, tds_SetNetworkDefaultGatewayResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetNetworkDefaultGateway",
            request,
            "SetNetworkDefaultGateway",
            "SetNetworkDefaultGatewayResponse",
            callback
        );
    }

    /**
     * @brief GetZeroConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetZeroConfiguration(const tds_GetZeroConfiguration& request,
                           const OnvifCallback<tds_GetZeroConfigurationResponse>& callback) {
        call_service<tds_GetZeroConfiguration, tds_GetZeroConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetZeroConfiguration",
            request,
            "GetZeroConfiguration",
            "GetZeroConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetZeroConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetZeroConfiguration(const tds_SetZeroConfiguration& request,
                           const OnvifCallback<tds_SetZeroConfigurationResponse>& callback) {
        call_service<tds_SetZeroConfiguration, tds_SetZeroConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetZeroConfiguration",
            request,
            "SetZeroConfiguration",
            "SetZeroConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetIPAddressFilter operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetIPAddressFilter(const tds_GetIPAddressFilter& request,
                           const OnvifCallback<tds_GetIPAddressFilterResponse>& callback) {
        call_service<tds_GetIPAddressFilter, tds_GetIPAddressFilterResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetIPAddressFilter",
            request,
            "GetIPAddressFilter",
            "GetIPAddressFilterResponse",
            callback
        );
    }

    /**
     * @brief SetIPAddressFilter operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetIPAddressFilter(const tds_SetIPAddressFilter& request,
                           const OnvifCallback<tds_SetIPAddressFilterResponse>& callback) {
        call_service<tds_SetIPAddressFilter, tds_SetIPAddressFilterResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetIPAddressFilter",
            request,
            "SetIPAddressFilter",
            "SetIPAddressFilterResponse",
            callback
        );
    }

    /**
     * @brief AddIPAddressFilter operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddIPAddressFilter(const tds_AddIPAddressFilter& request,
                           const OnvifCallback<tds_AddIPAddressFilterResponse>& callback) {
        call_service<tds_AddIPAddressFilter, tds_AddIPAddressFilterResponse>(
            "http://www.onvif.org/ver10/device/wsdl/AddIPAddressFilter",
            request,
            "AddIPAddressFilter",
            "AddIPAddressFilterResponse",
            callback
        );
    }

    /**
     * @brief RemoveIPAddressFilter operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemoveIPAddressFilter(const tds_RemoveIPAddressFilter& request,
                           const OnvifCallback<tds_RemoveIPAddressFilterResponse>& callback) {
        call_service<tds_RemoveIPAddressFilter, tds_RemoveIPAddressFilterResponse>(
            "http://www.onvif.org/ver10/device/wsdl/RemoveIPAddressFilter",
            request,
            "RemoveIPAddressFilter",
            "RemoveIPAddressFilterResponse",
            callback
        );
    }

    /**
     * @brief GetAccessPolicy operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAccessPolicy(const tds_GetAccessPolicy& request,
                           const OnvifCallback<tds_GetAccessPolicyResponse>& callback) {
        call_service<tds_GetAccessPolicy, tds_GetAccessPolicyResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetAccessPolicy",
            request,
            "GetAccessPolicy",
            "GetAccessPolicyResponse",
            callback
        );
    }

    /**
     * @brief SetAccessPolicy operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetAccessPolicy(const tds_SetAccessPolicy& request,
                           const OnvifCallback<tds_SetAccessPolicyResponse>& callback) {
        call_service<tds_SetAccessPolicy, tds_SetAccessPolicyResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetAccessPolicy",
            request,
            "SetAccessPolicy",
            "SetAccessPolicyResponse",
            callback
        );
    }

    /**
     * @brief GetRelayOutputs operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRelayOutputs(const tds_GetRelayOutputs& request,
                           const OnvifCallback<tds_GetRelayOutputsResponse>& callback) {
        call_service<tds_GetRelayOutputs, tds_GetRelayOutputsResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetRelayOutputs",
            request,
            "GetRelayOutputs",
            "GetRelayOutputsResponse",
            callback
        );
    }

    /**
     * @brief SetRelayOutputSettings operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetRelayOutputSettings(const tds_SetRelayOutputSettings& request,
                           const OnvifCallback<tds_SetRelayOutputSettingsResponse>& callback) {
        call_service<tds_SetRelayOutputSettings, tds_SetRelayOutputSettingsResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetRelayOutputSettings",
            request,
            "SetRelayOutputSettings",
            "SetRelayOutputSettingsResponse",
            callback
        );
    }

    /**
     * @brief SetRelayOutputState operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetRelayOutputState(const tds_SetRelayOutputState& request,
                           const OnvifCallback<tds_SetRelayOutputStateResponse>& callback) {
        call_service<tds_SetRelayOutputState, tds_SetRelayOutputStateResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetRelayOutputState",
            request,
            "SetRelayOutputState",
            "SetRelayOutputStateResponse",
            callback
        );
    }

    /**
     * @brief SendAuxiliaryCommand operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SendAuxiliaryCommand(const tds_SendAuxiliaryCommand& request,
                           const OnvifCallback<tds_SendAuxiliaryCommandResponse>& callback) {
        call_service<tds_SendAuxiliaryCommand, tds_SendAuxiliaryCommandResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SendAuxiliaryCommand",
            request,
            "SendAuxiliaryCommand",
            "SendAuxiliaryCommandResponse",
            callback
        );
    }

    /**
     * @brief GetDot11Capabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetDot11Capabilities(const tds_GetDot11Capabilities& request,
                           const OnvifCallback<tds_GetDot11CapabilitiesResponse>& callback) {
        call_service<tds_GetDot11Capabilities, tds_GetDot11CapabilitiesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetDot11Capabilities",
            request,
            "GetDot11Capabilities",
            "GetDot11CapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief GetDot11Status operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetDot11Status(const tds_GetDot11Status& request,
                           const OnvifCallback<tds_GetDot11StatusResponse>& callback) {
        call_service<tds_GetDot11Status, tds_GetDot11StatusResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetDot11Status",
            request,
            "GetDot11Status",
            "GetDot11StatusResponse",
            callback
        );
    }

    /**
     * @brief ScanAvailableDot11Networks operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void ScanAvailableDot11Networks(const tds_ScanAvailableDot11Networks& request,
                           const OnvifCallback<tds_ScanAvailableDot11NetworksResponse>& callback) {
        call_service<tds_ScanAvailableDot11Networks, tds_ScanAvailableDot11NetworksResponse>(
            "http://www.onvif.org/ver10/device/wsdl/ScanAvailableDot11Networks",
            request,
            "ScanAvailableDot11Networks",
            "ScanAvailableDot11NetworksResponse",
            callback
        );
    }

    /**
     * @brief GetSystemUris operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetSystemUris(const tds_GetSystemUris& request,
                           const OnvifCallback<tds_GetSystemUrisResponse>& callback) {
        call_service<tds_GetSystemUris, tds_GetSystemUrisResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetSystemUris",
            request,
            "GetSystemUris",
            "GetSystemUrisResponse",
            callback
        );
    }

    /**
     * @brief StartFirmwareUpgrade operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void StartFirmwareUpgrade(const tds_StartFirmwareUpgrade& request,
                           const OnvifCallback<tds_StartFirmwareUpgradeResponse>& callback) {
        call_service<tds_StartFirmwareUpgrade, tds_StartFirmwareUpgradeResponse>(
            "http://www.onvif.org/ver10/device/wsdl/StartFirmwareUpgrade",
            request,
            "StartFirmwareUpgrade",
            "StartFirmwareUpgradeResponse",
            callback
        );
    }

    /**
     * @brief UpgradeFirmware operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void UpgradeFirmware(const tds_UpgradeFirmware& request,
                           const OnvifCallback<tds_UpgradeFirmwareResponse>& callback) {
        call_service<tds_UpgradeFirmware, tds_UpgradeFirmwareResponse>(
            "http://www.onvif.org/ver10/device/wsdl/UpgradeFirmware",
            request,
            "UpgradeFirmware",
            "UpgradeFirmwareResponse",
            callback
        );
    }

    /**
     * @brief StartSystemRestore operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void StartSystemRestore(const tds_StartSystemRestore& request,
                           const OnvifCallback<tds_StartSystemRestoreResponse>& callback) {
        call_service<tds_StartSystemRestore, tds_StartSystemRestoreResponse>(
            "http://www.onvif.org/ver10/device/wsdl/StartSystemRestore",
            request,
            "StartSystemRestore",
            "StartSystemRestoreResponse",
            callback
        );
    }

    /**
     * @brief GetStorageConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetStorageConfigurations(const tds_GetStorageConfigurations& request,
                           const OnvifCallback<tds_GetStorageConfigurationsResponse>& callback) {
        call_service<tds_GetStorageConfigurations, tds_GetStorageConfigurationsResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetStorageConfigurations",
            request,
            "GetStorageConfigurations",
            "GetStorageConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief CreateStorageConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateStorageConfiguration(const tds_CreateStorageConfiguration& request,
                           const OnvifCallback<tds_CreateStorageConfigurationResponse>& callback) {
        call_service<tds_CreateStorageConfiguration, tds_CreateStorageConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/CreateStorageConfiguration",
            request,
            "CreateStorageConfiguration",
            "CreateStorageConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetStorageConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetStorageConfiguration(const tds_GetStorageConfiguration& request,
                           const OnvifCallback<tds_GetStorageConfigurationResponse>& callback) {
        call_service<tds_GetStorageConfiguration, tds_GetStorageConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetStorageConfiguration",
            request,
            "GetStorageConfiguration",
            "GetStorageConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetStorageConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetStorageConfiguration(const tds_SetStorageConfiguration& request,
                           const OnvifCallback<tds_SetStorageConfigurationResponse>& callback) {
        call_service<tds_SetStorageConfiguration, tds_SetStorageConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetStorageConfiguration",
            request,
            "SetStorageConfiguration",
            "SetStorageConfigurationResponse",
            callback
        );
    }

    /**
     * @brief DeleteStorageConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteStorageConfiguration(const tds_DeleteStorageConfiguration& request,
                           const OnvifCallback<tds_DeleteStorageConfigurationResponse>& callback) {
        call_service<tds_DeleteStorageConfiguration, tds_DeleteStorageConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/DeleteStorageConfiguration",
            request,
            "DeleteStorageConfiguration",
            "DeleteStorageConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetGeoLocation operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetGeoLocation(const tds_GetGeoLocation& request,
                           const OnvifCallback<tds_GetGeoLocationResponse>& callback) {
        call_service<tds_GetGeoLocation, tds_GetGeoLocationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetGeoLocation",
            request,
            "GetGeoLocation",
            "GetGeoLocationResponse",
            callback
        );
    }

    /**
     * @brief SetGeoLocation operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetGeoLocation(const tds_SetGeoLocation& request,
                           const OnvifCallback<tds_SetGeoLocationResponse>& callback) {
        call_service<tds_SetGeoLocation, tds_SetGeoLocationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetGeoLocation",
            request,
            "SetGeoLocation",
            "SetGeoLocationResponse",
            callback
        );
    }

    /**
     * @brief DeleteGeoLocation operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteGeoLocation(const tds_DeleteGeoLocation& request,
                           const OnvifCallback<tds_DeleteGeoLocationResponse>& callback) {
        call_service<tds_DeleteGeoLocation, tds_DeleteGeoLocationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/DeleteGeoLocation",
            request,
            "DeleteGeoLocation",
            "DeleteGeoLocationResponse",
            callback
        );
    }

    /**
     * @brief SetHashingAlgorithm operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetHashingAlgorithm(const tds_SetHashingAlgorithm& request,
                           const OnvifCallback<tds_SetHashingAlgorithmResponse>& callback) {
        call_service<tds_SetHashingAlgorithm, tds_SetHashingAlgorithmResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetHashingAlgorithm",
            request,
            "SetHashingAlgorithm",
            "SetHashingAlgorithmResponse",
            callback
        );
    }

    /**
     * @brief CreateCertificate operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateCertificate(const tds_CreateCertificate& request,
                           const OnvifCallback<tds_CreateCertificateResponse>& callback) {
        call_service<tds_CreateCertificate, tds_CreateCertificateResponse>(
            "http://www.onvif.org/ver10/device/wsdl/CreateCertificate",
            request,
            "CreateCertificate",
            "CreateCertificateResponse",
            callback
        );
    }

    /**
     * @brief GetCertificates operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCertificates(const tds_GetCertificates& request,
                           const OnvifCallback<tds_GetCertificatesResponse>& callback) {
        call_service<tds_GetCertificates, tds_GetCertificatesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetCertificates",
            request,
            "GetCertificates",
            "GetCertificatesResponse",
            callback
        );
    }

    /**
     * @brief GetCertificatesStatus operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCertificatesStatus(const tds_GetCertificatesStatus& request,
                           const OnvifCallback<tds_GetCertificatesStatusResponse>& callback) {
        call_service<tds_GetCertificatesStatus, tds_GetCertificatesStatusResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetCertificatesStatus",
            request,
            "GetCertificatesStatus",
            "GetCertificatesStatusResponse",
            callback
        );
    }

    /**
     * @brief SetCertificatesStatus operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetCertificatesStatus(const tds_SetCertificatesStatus& request,
                           const OnvifCallback<tds_SetCertificatesStatusResponse>& callback) {
        call_service<tds_SetCertificatesStatus, tds_SetCertificatesStatusResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetCertificatesStatus",
            request,
            "SetCertificatesStatus",
            "SetCertificatesStatusResponse",
            callback
        );
    }

    /**
     * @brief DeleteCertificates operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteCertificates(const tds_DeleteCertificates& request,
                           const OnvifCallback<tds_DeleteCertificatesResponse>& callback) {
        call_service<tds_DeleteCertificates, tds_DeleteCertificatesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/DeleteCertificates",
            request,
            "DeleteCertificates",
            "DeleteCertificatesResponse",
            callback
        );
    }

    /**
     * @brief GetPkcs10Request operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetPkcs10Request(const tds_GetPkcs10Request& request,
                           const OnvifCallback<tds_GetPkcs10RequestResponse>& callback) {
        call_service<tds_GetPkcs10Request, tds_GetPkcs10RequestResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetPkcs10Request",
            request,
            "GetPkcs10Request",
            "GetPkcs10RequestResponse",
            callback
        );
    }

    /**
     * @brief LoadCertificates operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void LoadCertificates(const tds_LoadCertificates& request,
                           const OnvifCallback<tds_LoadCertificatesResponse>& callback) {
        call_service<tds_LoadCertificates, tds_LoadCertificatesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/LoadCertificates",
            request,
            "LoadCertificates",
            "LoadCertificatesResponse",
            callback
        );
    }

    /**
     * @brief GetClientCertificateMode operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetClientCertificateMode(const tds_GetClientCertificateMode& request,
                           const OnvifCallback<tds_GetClientCertificateModeResponse>& callback) {
        call_service<tds_GetClientCertificateMode, tds_GetClientCertificateModeResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetClientCertificateMode",
            request,
            "GetClientCertificateMode",
            "GetClientCertificateModeResponse",
            callback
        );
    }

    /**
     * @brief SetClientCertificateMode operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetClientCertificateMode(const tds_SetClientCertificateMode& request,
                           const OnvifCallback<tds_SetClientCertificateModeResponse>& callback) {
        call_service<tds_SetClientCertificateMode, tds_SetClientCertificateModeResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetClientCertificateMode",
            request,
            "SetClientCertificateMode",
            "SetClientCertificateModeResponse",
            callback
        );
    }

    /**
     * @brief GetCACertificates operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCACertificates(const tds_GetCACertificates& request,
                           const OnvifCallback<tds_GetCACertificatesResponse>& callback) {
        call_service<tds_GetCACertificates, tds_GetCACertificatesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetCACertificates",
            request,
            "GetCACertificates",
            "GetCACertificatesResponse",
            callback
        );
    }

    /**
     * @brief LoadCertificateWithPrivateKey operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void LoadCertificateWithPrivateKey(const tds_LoadCertificateWithPrivateKey& request,
                           const OnvifCallback<tds_LoadCertificateWithPrivateKeyResponse>& callback) {
        call_service<tds_LoadCertificateWithPrivateKey, tds_LoadCertificateWithPrivateKeyResponse>(
            "http://www.onvif.org/ver10/device/wsdl/LoadCertificateWithPrivateKey",
            request,
            "LoadCertificateWithPrivateKey",
            "LoadCertificateWithPrivateKeyResponse",
            callback
        );
    }

    /**
     * @brief GetCertificateInformation operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCertificateInformation(const tds_GetCertificateInformation& request,
                           const OnvifCallback<tds_GetCertificateInformationResponse>& callback) {
        call_service<tds_GetCertificateInformation, tds_GetCertificateInformationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetCertificateInformation",
            request,
            "GetCertificateInformation",
            "GetCertificateInformationResponse",
            callback
        );
    }

    /**
     * @brief LoadCACertificates operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void LoadCACertificates(const tds_LoadCACertificates& request,
                           const OnvifCallback<tds_LoadCACertificatesResponse>& callback) {
        call_service<tds_LoadCACertificates, tds_LoadCACertificatesResponse>(
            "http://www.onvif.org/ver10/device/wsdl/LoadCACertificates",
            request,
            "LoadCACertificates",
            "LoadCACertificatesResponse",
            callback
        );
    }

    /**
     * @brief CreateDot1XConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateDot1XConfiguration(const tds_CreateDot1XConfiguration& request,
                           const OnvifCallback<tds_CreateDot1XConfigurationResponse>& callback) {
        call_service<tds_CreateDot1XConfiguration, tds_CreateDot1XConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/CreateDot1XConfiguration",
            request,
            "CreateDot1XConfiguration",
            "CreateDot1XConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetDot1XConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetDot1XConfiguration(const tds_SetDot1XConfiguration& request,
                           const OnvifCallback<tds_SetDot1XConfigurationResponse>& callback) {
        call_service<tds_SetDot1XConfiguration, tds_SetDot1XConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/SetDot1XConfiguration",
            request,
            "SetDot1XConfiguration",
            "SetDot1XConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetDot1XConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetDot1XConfiguration(const tds_GetDot1XConfiguration& request,
                           const OnvifCallback<tds_GetDot1XConfigurationResponse>& callback) {
        call_service<tds_GetDot1XConfiguration, tds_GetDot1XConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetDot1XConfiguration",
            request,
            "GetDot1XConfiguration",
            "GetDot1XConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetDot1XConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetDot1XConfigurations(const tds_GetDot1XConfigurations& request,
                           const OnvifCallback<tds_GetDot1XConfigurationsResponse>& callback) {
        call_service<tds_GetDot1XConfigurations, tds_GetDot1XConfigurationsResponse>(
            "http://www.onvif.org/ver10/device/wsdl/GetDot1XConfigurations",
            request,
            "GetDot1XConfigurations",
            "GetDot1XConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief DeleteDot1XConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteDot1XConfiguration(const tds_DeleteDot1XConfiguration& request,
                           const OnvifCallback<tds_DeleteDot1XConfigurationResponse>& callback) {
        call_service<tds_DeleteDot1XConfiguration, tds_DeleteDot1XConfigurationResponse>(
            "http://www.onvif.org/ver10/device/wsdl/DeleteDot1XConfiguration",
            request,
            "DeleteDot1XConfiguration",
            "DeleteDot1XConfigurationResponse",
            callback
        );
    }

    const char *get_namespace_prefix() const override {
        return TARGET_NAMESPACE_PREFIX;
    }

    const char *get_namespace_uri() const override {
        return TARGET_NAMESPACE;
    }

    static constexpr const char* TARGET_NAMESPACE = "http://www.onvif.org/ver10/device/wsdl";
    static constexpr const char* TARGET_NAMESPACE_PREFIX = "tds";
};

} // namespace libonvif_client
