/**
 * @file EventClient.h
 * @brief EventPortTypeService client (header-only)
 * @note This file is auto-generated by wsdl_parser2, do not modify manually
 */

#pragma once

#include <libonvif_client/core/onvif_service_base.h>
#include <libonvif_client/core/onvif_callback.h>
#include <libonvif_client/types/tev.h>
#include <libonvif_client/types/wsnt.h>

namespace libonvif_client {

/**
 * @brief EventPortTypeService client
 * @namespace http://www.onvif.org/ver10/events/wsdl
 */
class EventClient : public OnvifServiceBase {
public:
    /**
     * @brief Constructor
     * @param service_url ONVIF service endpoint URL
     * @param http_client HTTP client implementation (user provided)
     * @param username Authentication username (optional)
     * @param password Authentication password (optional)
     */
    EventClient(const std::string& service_url,
                    const std::shared_ptr<IHttpClient>& http_client,
                    const std::string& username = "",
                    const std::string& password = "")
        : OnvifServiceBase(service_url, http_client, username, password) {
    }

    /**
     * @brief GetServiceCapabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetServiceCapabilities(const tev_GetServiceCapabilities& request,
                           const OnvifCallback<tev_GetServiceCapabilitiesResponse>& callback) {
        call_service<tev_GetServiceCapabilities, tev_GetServiceCapabilitiesResponse>(
            "http://www.onvif.org/ver10/events/wsdl/EventPortType/GetServiceCapabilitiesRequest",
            request,
            "GetServiceCapabilities",
            "GetServiceCapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief CreatePullPointSubscription operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreatePullPointSubscription(const tev_CreatePullPointSubscription& request,
                           const OnvifCallback<tev_CreatePullPointSubscriptionResponse>& callback) {
        call_service<tev_CreatePullPointSubscription, tev_CreatePullPointSubscriptionResponse>(
            "http://www.onvif.org/ver10/events/wsdl/EventPortType/CreatePullPointSubscriptionRequest",
            request,
            "CreatePullPointSubscription",
            "CreatePullPointSubscriptionResponse",
            callback
        );
    }

    /**
     * @brief GetEventProperties operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetEventProperties(const tev_GetEventProperties& request,
                           const OnvifCallback<tev_GetEventPropertiesResponse>& callback) {
        call_service<tev_GetEventProperties, tev_GetEventPropertiesResponse>(
            "http://www.onvif.org/ver10/events/wsdl/EventPortType/GetEventPropertiesRequest",
            request,
            "GetEventProperties",
            "GetEventPropertiesResponse",
            callback
        );
    }

    /**
     * @brief AddEventBroker operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddEventBroker(const tev_AddEventBroker& request,
                           const OnvifCallback<tev_AddEventBrokerResponse>& callback) {
        call_service<tev_AddEventBroker, tev_AddEventBrokerResponse>(
            "http://www.onvif.org/ver10/events/wsdl/EventPortType/AddEventBrokerRequest",
            request,
            "AddEventBroker",
            "AddEventBrokerResponse",
            callback
        );
    }

    /**
     * @brief DeleteEventBroker operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteEventBroker(const tev_DeleteEventBroker& request,
                           const OnvifCallback<tev_DeleteEventBrokerResponse>& callback) {
        call_service<tev_DeleteEventBroker, tev_DeleteEventBrokerResponse>(
            "http://www.onvif.org/ver10/events/wsdl/EventPortType/DeleteEventBrokerRequest",
            request,
            "DeleteEventBroker",
            "DeleteEventBrokerResponse",
            callback
        );
    }

    /**
     * @brief GetEventBrokers operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetEventBrokers(const tev_GetEventBrokers& request,
                           const OnvifCallback<tev_GetEventBrokersResponse>& callback) {
        call_service<tev_GetEventBrokers, tev_GetEventBrokersResponse>(
            "http://www.onvif.org/ver10/events/wsdl/EventPortType/GetEventBrokersRequest",
            request,
            "GetEventBrokers",
            "GetEventBrokersResponse",
            callback
        );
    }

    /**
     * @brief Notify operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void Notify(const wsnt_Notify& request,
                           const OnvifSimpleCallback& callback) {
        call_service_ex<wsnt_Notify, void>(
            "http://www.onvif.org/ver10/events/wsdl/Notify",
            request,
            "Notify",
            "NotifyResponse",
            "wsntw",
            callback
        );
    }

    /**
     * @brief Subscribe operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void Subscribe(const wsnt_Subscribe& request,
                           const OnvifCallback<wsnt_SubscribeResponse>& callback) {
        call_service_ex<wsnt_Subscribe, wsnt_SubscribeResponse>(
            "http://www.onvif.org/ver10/events/wsdl/Subscribe",
            request,
            "Subscribe",
            "SubscribeResponse",
            "wsntw",
            callback
        );
    }

    /**
     * @brief GetCurrentMessage operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCurrentMessage(const wsnt_GetCurrentMessage& request,
                           const OnvifCallback<wsnt_GetCurrentMessageResponse>& callback) {
        call_service_ex<wsnt_GetCurrentMessage, wsnt_GetCurrentMessageResponse>(
            "http://www.onvif.org/ver10/events/wsdl/GetCurrentMessage",
            request,
            "GetCurrentMessage",
            "GetCurrentMessageResponse",
            "wsntw",
            callback
        );
    }

    /**
     * @brief GetMessages operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetMessages(const wsnt_GetMessages& request,
                           const OnvifCallback<wsnt_GetMessagesResponse>& callback) {
        call_service_ex<wsnt_GetMessages, wsnt_GetMessagesResponse>(
            "http://www.onvif.org/ver10/events/wsdl/GetMessages",
            request,
            "GetMessages",
            "GetMessagesResponse",
            "wsntw",
            callback
        );
    }

    /**
     * @brief DestroyPullPoint operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DestroyPullPoint(const wsnt_DestroyPullPoint& request,
                           const OnvifCallback<wsnt_DestroyPullPointResponse>& callback) {
        call_service_ex<wsnt_DestroyPullPoint, wsnt_DestroyPullPointResponse>(
            "http://www.onvif.org/ver10/events/wsdl/DestroyPullPoint",
            request,
            "DestroyPullPoint",
            "DestroyPullPointResponse",
            "wsntw",
            callback
        );
    }

    /**
     * @brief CreatePullPoint operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreatePullPoint(const wsnt_CreatePullPoint& request,
                           const OnvifCallback<wsnt_CreatePullPointResponse>& callback) {
        call_service_ex<wsnt_CreatePullPoint, wsnt_CreatePullPointResponse>(
            "http://www.onvif.org/ver10/events/wsdl/CreatePullPoint",
            request,
            "CreatePullPoint",
            "CreatePullPointResponse",
            "wsntw",
            callback
        );
    }

    /**
     * @brief Renew operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void Renew(const wsnt_Renew& request,
                           const OnvifCallback<wsnt_RenewResponse>& callback) {
        call_service_ex<wsnt_Renew, wsnt_RenewResponse>(
            "http://www.onvif.org/ver10/events/wsdl/Renew",
            request,
            "Renew",
            "RenewResponse",
            "wsntw",
            callback
        );
    }

    /**
     * @brief Unsubscribe operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void Unsubscribe(const wsnt_Unsubscribe& request,
                           const OnvifCallback<wsnt_UnsubscribeResponse>& callback) {
        call_service_ex<wsnt_Unsubscribe, wsnt_UnsubscribeResponse>(
            "http://www.onvif.org/ver10/events/wsdl/Unsubscribe",
            request,
            "Unsubscribe",
            "UnsubscribeResponse",
            "wsntw",
            callback
        );
    }

    /**
     * @brief PauseSubscription operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void PauseSubscription(const wsnt_PauseSubscription& request,
                           const OnvifCallback<wsnt_PauseSubscriptionResponse>& callback) {
        call_service_ex<wsnt_PauseSubscription, wsnt_PauseSubscriptionResponse>(
            "http://www.onvif.org/ver10/events/wsdl/PauseSubscription",
            request,
            "PauseSubscription",
            "PauseSubscriptionResponse",
            "wsntw",
            callback
        );
    }

    /**
     * @brief ResumeSubscription operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void ResumeSubscription(const wsnt_ResumeSubscription& request,
                           const OnvifCallback<wsnt_ResumeSubscriptionResponse>& callback) {
        call_service_ex<wsnt_ResumeSubscription, wsnt_ResumeSubscriptionResponse>(
            "http://www.onvif.org/ver10/events/wsdl/ResumeSubscription",
            request,
            "ResumeSubscription",
            "ResumeSubscriptionResponse",
            "wsntw",
            callback
        );
    }

    /**
     * @brief PullMessages operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void PullMessages(const tev_PullMessages& request,
                           const OnvifCallback<tev_PullMessagesResponse>& callback) {
        call_service<tev_PullMessages, tev_PullMessagesResponse>(
            "http://www.onvif.org/ver10/events/wsdl/PullPointSubscription/PullMessagesRequest",
            request,
            "PullMessages",
            "PullMessagesResponse",
            callback
        );
    }

    /**
     * @brief Seek operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void Seek(const tev_Seek& request,
                           const OnvifCallback<tev_SeekResponse>& callback) {
        call_service<tev_Seek, tev_SeekResponse>(
            "http://www.onvif.org/ver10/events/wsdl/PullPointSubscription/SeekRequest",
            request,
            "Seek",
            "SeekResponse",
            callback
        );
    }

    /**
     * @brief SetSynchronizationPoint operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetSynchronizationPoint(const tev_SetSynchronizationPoint& request,
                           const OnvifCallback<tev_SetSynchronizationPointResponse>& callback) {
        call_service<tev_SetSynchronizationPoint, tev_SetSynchronizationPointResponse>(
            "http://www.onvif.org/ver10/events/wsdl/PullPointSubscription/SetSynchronizationPointRequest",
            request,
            "SetSynchronizationPoint",
            "SetSynchronizationPointResponse",
            callback
        );
    }

    const char *get_namespace_prefix() const override {
        return TARGET_NAMESPACE_PREFIX;
    }

    const char *get_namespace_uri() const override {
        return TARGET_NAMESPACE;
    }

    static constexpr const char* TARGET_NAMESPACE = "http://www.onvif.org/ver10/events/wsdl";
    static constexpr const char* TARGET_NAMESPACE_PREFIX = "tev";
};

} // namespace libonvif_client
