/**
 * @file ImagingPortClient.h
 * @brief ImagingPortService client (header-only)
 * @note This file is auto-generated by wsdl_parser2, do not modify manually
 */

#pragma once

#include <libonvif_client/core/onvif_service_base.h>
#include <libonvif_client/core/onvif_callback.h>
#include <libonvif_client/types/timg.h>

namespace libonvif_client {

/**
 * @brief ImagingPortService client
 * @namespace http://www.onvif.org/ver20/imaging/wsdl
 */
class ImagingPortClient : public OnvifServiceBase {
public:
    /**
     * @brief Constructor
     * @param service_url ONVIF service endpoint URL
     * @param http_client HTTP client implementation (user provided)
     * @param username Authentication username (optional)
     * @param password Authentication password (optional)
     */
    ImagingPortClient(const std::string& service_url,
                    const std::shared_ptr<IHttpClient>& http_client,
                    const std::string& username = "",
                    const std::string& password = "")
        : OnvifServiceBase(service_url, http_client, username, password) {
    }

    /**
     * @brief GetServiceCapabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetServiceCapabilities(const timg_GetServiceCapabilities& request,
                           const OnvifCallback<timg_GetServiceCapabilitiesResponse>& callback) {
        call_service<timg_GetServiceCapabilities, timg_GetServiceCapabilitiesResponse>(
            "http://www.onvif.org/ver20/imaging/wsdl/GetServiceCapabilities",
            request,
            "GetServiceCapabilities",
            "GetServiceCapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief GetImagingSettings operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetImagingSettings(const timg_GetImagingSettings& request,
                           const OnvifCallback<timg_GetImagingSettingsResponse>& callback) {
        call_service<timg_GetImagingSettings, timg_GetImagingSettingsResponse>(
            "http://www.onvif.org/ver20/imaging/wsdl/GetImagingSettings",
            request,
            "GetImagingSettings",
            "GetImagingSettingsResponse",
            callback
        );
    }

    /**
     * @brief SetImagingSettings operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetImagingSettings(const timg_SetImagingSettings& request,
                           const OnvifCallback<timg_SetImagingSettingsResponse>& callback) {
        call_service<timg_SetImagingSettings, timg_SetImagingSettingsResponse>(
            "http://www.onvif.org/ver20/imaging/wsdl/SetImagingSettings",
            request,
            "SetImagingSettings",
            "SetImagingSettingsResponse",
            callback
        );
    }

    /**
     * @brief GetOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetOptions(const timg_GetOptions& request,
                           const OnvifCallback<timg_GetOptionsResponse>& callback) {
        call_service<timg_GetOptions, timg_GetOptionsResponse>(
            "http://www.onvif.org/ver20/imaging/wsdl/GetOptions",
            request,
            "GetOptions",
            "GetOptionsResponse",
            callback
        );
    }

    /**
     * @brief Move operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void Move(const timg_Move& request,
                           const OnvifCallback<timg_MoveResponse>& callback) {
        call_service<timg_Move, timg_MoveResponse>(
            "http://www.onvif.org/ver20/imaging/wsdl/Move",
            request,
            "Move",
            "MoveResponse",
            callback
        );
    }

    /**
     * @brief GetMoveOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetMoveOptions(const timg_GetMoveOptions& request,
                           const OnvifCallback<timg_GetMoveOptionsResponse>& callback) {
        call_service<timg_GetMoveOptions, timg_GetMoveOptionsResponse>(
            "http://www.onvif.org/ver20/imaging/wsdl/GetMoveOptions",
            request,
            "GetMoveOptions",
            "GetMoveOptionsResponse",
            callback
        );
    }

    /**
     * @brief Stop operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void Stop(const timg_Stop& request,
                           const OnvifCallback<timg_StopResponse>& callback) {
        call_service<timg_Stop, timg_StopResponse>(
            "http://www.onvif.org/ver20/imaging/wsdl/FocusStop",
            request,
            "Stop",
            "StopResponse",
            callback
        );
    }

    /**
     * @brief GetStatus operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetStatus(const timg_GetStatus& request,
                           const OnvifCallback<timg_GetStatusResponse>& callback) {
        call_service<timg_GetStatus, timg_GetStatusResponse>(
            "http://www.onvif.org/ver20/imaging/wsdl/GetStatus",
            request,
            "GetStatus",
            "GetStatusResponse",
            callback
        );
    }

    /**
     * @brief GetPresets operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetPresets(const timg_GetPresets& request,
                           const OnvifCallback<timg_GetPresetsResponse>& callback) {
        call_service<timg_GetPresets, timg_GetPresetsResponse>(
            "http://www.onvif.org/ver20/imaging/wsdl/GetPresets",
            request,
            "GetPresets",
            "GetPresetsResponse",
            callback
        );
    }

    /**
     * @brief GetCurrentPreset operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCurrentPreset(const timg_GetCurrentPreset& request,
                           const OnvifCallback<timg_GetCurrentPresetResponse>& callback) {
        call_service<timg_GetCurrentPreset, timg_GetCurrentPresetResponse>(
            "http://www.onvif.org/ver20/imaging/wsdl/GetCurrentPreset",
            request,
            "GetCurrentPreset",
            "GetCurrentPresetResponse",
            callback
        );
    }

    /**
     * @brief SetCurrentPreset operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetCurrentPreset(const timg_SetCurrentPreset& request,
                           const OnvifCallback<timg_SetCurrentPresetResponse>& callback) {
        call_service<timg_SetCurrentPreset, timg_SetCurrentPresetResponse>(
            "http://www.onvif.org/ver20/imaging/wsdl/SetCurrentPreset",
            request,
            "SetCurrentPreset",
            "SetCurrentPresetResponse",
            callback
        );
    }

    const char *get_namespace_prefix() const override {
        return TARGET_NAMESPACE_PREFIX;
    }

    const char *get_namespace_uri() const override {
        return TARGET_NAMESPACE;
    }

    static constexpr const char* TARGET_NAMESPACE = "http://www.onvif.org/ver20/imaging/wsdl";
    static constexpr const char* TARGET_NAMESPACE_PREFIX = "timg";
};

} // namespace libonvif_client
