/**
 * @file Media2Client.h
 * @brief Media2Service client (header-only)
 * @note This file is auto-generated by wsdl_parser2, do not modify manually
 */

#pragma once

#include <libonvif_client/core/onvif_service_base.h>
#include <libonvif_client/core/onvif_callback.h>
#include <libonvif_client/types/tr2.h>

namespace libonvif_client {

/**
 * @brief Media2Service client
 * @namespace http://www.onvif.org/ver20/media/wsdl
 */
class Media2Client : public OnvifServiceBase {
public:
    /**
     * @brief Constructor
     * @param service_url ONVIF service endpoint URL
     * @param http_client HTTP client implementation (user provided)
     * @param username Authentication username (optional)
     * @param password Authentication password (optional)
     */
    Media2Client(const std::string& service_url,
                    const std::shared_ptr<IHttpClient>& http_client,
                    const std::string& username = "",
                    const std::string& password = "")
        : OnvifServiceBase(service_url, http_client, username, password) {
    }

    /**
     * @brief GetServiceCapabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetServiceCapabilities(const tr2_GetServiceCapabilities& request,
                           const OnvifCallback<tr2_GetServiceCapabilitiesResponse>& callback) {
        call_service<tr2_GetServiceCapabilities, tr2_GetServiceCapabilitiesResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetServiceCapabilities",
            request,
            "GetServiceCapabilities",
            "GetServiceCapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief CreateProfile operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateProfile(const tr2_CreateProfile& request,
                           const OnvifCallback<tr2_CreateProfileResponse>& callback) {
        call_service<tr2_CreateProfile, tr2_CreateProfileResponse>(
            "http://www.onvif.org/ver20/media/wsdl/CreateProfile",
            request,
            "CreateProfile",
            "CreateProfileResponse",
            callback
        );
    }

    /**
     * @brief GetProfiles operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetProfiles(const tr2_GetProfiles& request,
                           const OnvifCallback<tr2_GetProfilesResponse>& callback) {
        call_service<tr2_GetProfiles, tr2_GetProfilesResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetProfiles",
            request,
            "GetProfiles",
            "GetProfilesResponse",
            callback
        );
    }

    /**
     * @brief AddConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddConfiguration(const tr2_AddConfiguration& request,
                           const OnvifCallback<tr2_AddConfigurationResponse>& callback) {
        call_service<tr2_AddConfiguration, tr2_AddConfigurationResponse>(
            "http://www.onvif.org/ver20/media/wsdl/AddConfiguration",
            request,
            "AddConfiguration",
            "AddConfigurationResponse",
            callback
        );
    }

    /**
     * @brief RemoveConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemoveConfiguration(const tr2_RemoveConfiguration& request,
                           const OnvifCallback<tr2_RemoveConfigurationResponse>& callback) {
        call_service<tr2_RemoveConfiguration, tr2_RemoveConfigurationResponse>(
            "http://www.onvif.org/ver20/media/wsdl/RemoveConfiguration",
            request,
            "RemoveConfiguration",
            "RemoveConfigurationResponse",
            callback
        );
    }

    /**
     * @brief DeleteProfile operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteProfile(const tr2_DeleteProfile& request,
                           const OnvifCallback<tr2_DeleteProfileResponse>& callback) {
        call_service<tr2_DeleteProfile, tr2_DeleteProfileResponse>(
            "http://www.onvif.org/ver20/media/wsdl/DeleteProfile",
            request,
            "DeleteProfile",
            "DeleteProfileResponse",
            callback
        );
    }

    /**
     * @brief GetVideoSourceConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoSourceConfigurations(const tr2_GetVideoSourceConfigurations& request,
                           const OnvifCallback<tr2_GetVideoSourceConfigurationsResponse>& callback) {
        call_service<tr2_GetVideoSourceConfigurations, tr2_GetVideoSourceConfigurationsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetVideoSourceConfigurations",
            request,
            "GetVideoSourceConfigurations",
            "GetVideoSourceConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetVideoEncoderConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoEncoderConfigurations(const tr2_GetVideoEncoderConfigurations& request,
                           const OnvifCallback<tr2_GetVideoEncoderConfigurationsResponse>& callback) {
        call_service<tr2_GetVideoEncoderConfigurations, tr2_GetVideoEncoderConfigurationsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetVideoEncoderConfigurations",
            request,
            "GetVideoEncoderConfigurations",
            "GetVideoEncoderConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioSourceConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioSourceConfigurations(const tr2_GetAudioSourceConfigurations& request,
                           const OnvifCallback<tr2_GetAudioSourceConfigurationsResponse>& callback) {
        call_service<tr2_GetAudioSourceConfigurations, tr2_GetAudioSourceConfigurationsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetAudioSourceConfigurations/",
            request,
            "GetAudioSourceConfigurations",
            "GetAudioSourceConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioEncoderConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioEncoderConfigurations(const tr2_GetAudioEncoderConfigurations& request,
                           const OnvifCallback<tr2_GetAudioEncoderConfigurationsResponse>& callback) {
        call_service<tr2_GetAudioEncoderConfigurations, tr2_GetAudioEncoderConfigurationsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetAudioEncoderConfigurations",
            request,
            "GetAudioEncoderConfigurations",
            "GetAudioEncoderConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetAnalyticsConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAnalyticsConfigurations(const tr2_GetAnalyticsConfigurations& request,
                           const OnvifCallback<tr2_GetAnalyticsConfigurationsResponse>& callback) {
        call_service<tr2_GetAnalyticsConfigurations, tr2_GetAnalyticsConfigurationsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetAnalyticsConfigurations",
            request,
            "GetAnalyticsConfigurations",
            "GetAnalyticsConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetMetadataConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetMetadataConfigurations(const tr2_GetMetadataConfigurations& request,
                           const OnvifCallback<tr2_GetMetadataConfigurationsResponse>& callback) {
        call_service<tr2_GetMetadataConfigurations, tr2_GetMetadataConfigurationsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetMetadataConfigurations",
            request,
            "GetMetadataConfigurations",
            "GetMetadataConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioOutputConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioOutputConfigurations(const tr2_GetAudioOutputConfigurations& request,
                           const OnvifCallback<tr2_GetAudioOutputConfigurationsResponse>& callback) {
        call_service<tr2_GetAudioOutputConfigurations, tr2_GetAudioOutputConfigurationsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetAudioOutputConfigurations",
            request,
            "GetAudioOutputConfigurations",
            "GetAudioOutputConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioDecoderConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioDecoderConfigurations(const tr2_GetAudioDecoderConfigurations& request,
                           const OnvifCallback<tr2_GetAudioDecoderConfigurationsResponse>& callback) {
        call_service<tr2_GetAudioDecoderConfigurations, tr2_GetAudioDecoderConfigurationsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetAudioDecoderConfigurations",
            request,
            "GetAudioDecoderConfigurations",
            "GetAudioDecoderConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief SetVideoSourceConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetVideoSourceConfiguration(const tr2_SetVideoSourceConfiguration& request,
                           const OnvifCallback<tr2_SetVideoSourceConfigurationResponse>& callback) {
        call_service<tr2_SetVideoSourceConfiguration, tr2_SetVideoSourceConfigurationResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetVideoSourceConfiguration",
            request,
            "SetVideoSourceConfiguration",
            "SetVideoSourceConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetVideoEncoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetVideoEncoderConfiguration(const tr2_SetVideoEncoderConfiguration& request,
                           const OnvifCallback<tr2_SetVideoEncoderConfigurationResponse>& callback) {
        call_service<tr2_SetVideoEncoderConfiguration, tr2_SetVideoEncoderConfigurationResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetVideoEncoderConfiguration",
            request,
            "SetVideoEncoderConfiguration",
            "SetVideoEncoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetAudioSourceConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetAudioSourceConfiguration(const tr2_SetAudioSourceConfiguration& request,
                           const OnvifCallback<tr2_SetAudioSourceConfigurationResponse>& callback) {
        call_service<tr2_SetAudioSourceConfiguration, tr2_SetAudioSourceConfigurationResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetAudioSourceConfiguration",
            request,
            "SetAudioSourceConfiguration",
            "SetAudioSourceConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetAudioEncoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetAudioEncoderConfiguration(const tr2_SetAudioEncoderConfiguration& request,
                           const OnvifCallback<tr2_SetAudioEncoderConfigurationResponse>& callback) {
        call_service<tr2_SetAudioEncoderConfiguration, tr2_SetAudioEncoderConfigurationResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetAudioEncoderConfiguration",
            request,
            "SetAudioEncoderConfiguration",
            "SetAudioEncoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetMetadataConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetMetadataConfiguration(const tr2_SetMetadataConfiguration& request,
                           const OnvifCallback<tr2_SetMetadataConfigurationResponse>& callback) {
        call_service<tr2_SetMetadataConfiguration, tr2_SetMetadataConfigurationResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetMetadataConfiguration",
            request,
            "SetMetadataConfiguration",
            "SetMetadataConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetAudioOutputConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetAudioOutputConfiguration(const tr2_SetAudioOutputConfiguration& request,
                           const OnvifCallback<tr2_SetAudioOutputConfigurationResponse>& callback) {
        call_service<tr2_SetAudioOutputConfiguration, tr2_SetAudioOutputConfigurationResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetAudioOutputConfiguration",
            request,
            "SetAudioOutputConfiguration",
            "SetAudioOutputConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetAudioDecoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetAudioDecoderConfiguration(const tr2_SetAudioDecoderConfiguration& request,
                           const OnvifCallback<tr2_SetAudioDecoderConfigurationResponse>& callback) {
        call_service<tr2_SetAudioDecoderConfiguration, tr2_SetAudioDecoderConfigurationResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetAudioDecoderConfiguration",
            request,
            "SetAudioDecoderConfiguration",
            "SetAudioDecoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetVideoSourceConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoSourceConfigurationOptions(const tr2_GetVideoSourceConfigurationOptions& request,
                           const OnvifCallback<tr2_GetVideoSourceConfigurationOptionsResponse>& callback) {
        call_service<tr2_GetVideoSourceConfigurationOptions, tr2_GetVideoSourceConfigurationOptionsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetVideoSourceConfigurationOptions/",
            request,
            "GetVideoSourceConfigurationOptions",
            "GetVideoSourceConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetVideoEncoderConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoEncoderConfigurationOptions(const tr2_GetVideoEncoderConfigurationOptions& request,
                           const OnvifCallback<tr2_GetVideoEncoderConfigurationOptionsResponse>& callback) {
        call_service<tr2_GetVideoEncoderConfigurationOptions, tr2_GetVideoEncoderConfigurationOptionsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetVideoEncoderConfigurationOptions",
            request,
            "GetVideoEncoderConfigurationOptions",
            "GetVideoEncoderConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioSourceConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioSourceConfigurationOptions(const tr2_GetAudioSourceConfigurationOptions& request,
                           const OnvifCallback<tr2_GetAudioSourceConfigurationOptionsResponse>& callback) {
        call_service<tr2_GetAudioSourceConfigurationOptions, tr2_GetAudioSourceConfigurationOptionsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetAudioSourceConfigurationOptions",
            request,
            "GetAudioSourceConfigurationOptions",
            "GetAudioSourceConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioEncoderConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioEncoderConfigurationOptions(const tr2_GetAudioEncoderConfigurationOptions& request,
                           const OnvifCallback<tr2_GetAudioEncoderConfigurationOptionsResponse>& callback) {
        call_service<tr2_GetAudioEncoderConfigurationOptions, tr2_GetAudioEncoderConfigurationOptionsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetAudioEncoderConfigurationOptions",
            request,
            "GetAudioEncoderConfigurationOptions",
            "GetAudioEncoderConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetMetadataConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetMetadataConfigurationOptions(const tr2_GetMetadataConfigurationOptions& request,
                           const OnvifCallback<tr2_GetMetadataConfigurationOptionsResponse>& callback) {
        call_service<tr2_GetMetadataConfigurationOptions, tr2_GetMetadataConfigurationOptionsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetMetadataConfigurationOptions",
            request,
            "GetMetadataConfigurationOptions",
            "GetMetadataConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioOutputConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioOutputConfigurationOptions(const tr2_GetAudioOutputConfigurationOptions& request,
                           const OnvifCallback<tr2_GetAudioOutputConfigurationOptionsResponse>& callback) {
        call_service<tr2_GetAudioOutputConfigurationOptions, tr2_GetAudioOutputConfigurationOptionsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetAudioOutputConfigurationOptions",
            request,
            "GetAudioOutputConfigurationOptions",
            "GetAudioOutputConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioDecoderConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioDecoderConfigurationOptions(const tr2_GetAudioDecoderConfigurationOptions& request,
                           const OnvifCallback<tr2_GetAudioDecoderConfigurationOptionsResponse>& callback) {
        call_service<tr2_GetAudioDecoderConfigurationOptions, tr2_GetAudioDecoderConfigurationOptionsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetAudioDecoderConfigurationOptions",
            request,
            "GetAudioDecoderConfigurationOptions",
            "GetAudioDecoderConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief SetEQPreset operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetEQPreset(const tr2_SetEQPresetConfiguration& request,
                           const OnvifCallback<tr2_SetEQPresetConfigurationResponse>& callback) {
        call_service<tr2_SetEQPresetConfiguration, tr2_SetEQPresetConfigurationResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetEQPreset",
            request,
            "SetEQPreset",
            "SetEQPresetResponse",
            callback
        );
    }

    /**
     * @brief GetVideoEncoderInstances operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoEncoderInstances(const tr2_GetVideoEncoderInstances& request,
                           const OnvifCallback<tr2_GetVideoEncoderInstancesResponse>& callback) {
        call_service<tr2_GetVideoEncoderInstances, tr2_GetVideoEncoderInstancesResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetVideoEncoderInstances",
            request,
            "GetVideoEncoderInstances",
            "GetVideoEncoderInstancesResponse",
            callback
        );
    }

    /**
     * @brief GetStreamUri operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetStreamUri(const tr2_GetStreamUri& request,
                           const OnvifCallback<tr2_GetStreamUriResponse>& callback) {
        call_service<tr2_GetStreamUri, tr2_GetStreamUriResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetStreamUri",
            request,
            "GetStreamUri",
            "GetStreamUriResponse",
            callback
        );
    }

    /**
     * @brief StartMulticastStreaming operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void StartMulticastStreaming(const tr2_StartMulticastStreaming& request,
                           const OnvifCallback<tr2_StartMulticastStreamingResponse>& callback) {
        call_service<tr2_StartMulticastStreaming, tr2_StartMulticastStreamingResponse>(
            "http://www.onvif.org/ver20/media/wsdl/StartMulticastStreaming",
            request,
            "StartMulticastStreaming",
            "StartMulticastStreamingResponse",
            callback
        );
    }

    /**
     * @brief StopMulticastStreaming operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void StopMulticastStreaming(const tr2_StopMulticastStreaming& request,
                           const OnvifCallback<tr2_StopMulticastStreamingResponse>& callback) {
        call_service<tr2_StopMulticastStreaming, tr2_StopMulticastStreamingResponse>(
            "http://www.onvif.org/ver20/media/wsdl/StopMulticastStreaming",
            request,
            "StopMulticastStreaming",
            "StopMulticastStreamingResponse",
            callback
        );
    }

    /**
     * @brief SetSynchronizationPoint operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetSynchronizationPoint(const tr2_SetSynchronizationPoint& request,
                           const OnvifCallback<tr2_SetSynchronizationPointResponse>& callback) {
        call_service<tr2_SetSynchronizationPoint, tr2_SetSynchronizationPointResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetSynchronizationPoint",
            request,
            "SetSynchronizationPoint",
            "SetSynchronizationPointResponse",
            callback
        );
    }

    /**
     * @brief GetSnapshotUri operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetSnapshotUri(const tr2_GetSnapshotUri& request,
                           const OnvifCallback<tr2_GetSnapshotUriResponse>& callback) {
        call_service<tr2_GetSnapshotUri, tr2_GetSnapshotUriResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetSnapshotUri",
            request,
            "GetSnapshotUri",
            "GetSnapshotUriResponse",
            callback
        );
    }

    /**
     * @brief GetVideoSourceModes operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoSourceModes(const tr2_GetVideoSourceModes& request,
                           const OnvifCallback<tr2_GetVideoSourceModesResponse>& callback) {
        call_service<tr2_GetVideoSourceModes, tr2_GetVideoSourceModesResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetVideoSourceModes",
            request,
            "GetVideoSourceModes",
            "GetVideoSourceModesResponse",
            callback
        );
    }

    /**
     * @brief SetVideoSourceMode operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetVideoSourceMode(const tr2_SetVideoSourceMode& request,
                           const OnvifCallback<tr2_SetVideoSourceModeResponse>& callback) {
        call_service<tr2_SetVideoSourceMode, tr2_SetVideoSourceModeResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetVideoSourceMode",
            request,
            "SetVideoSourceMode",
            "SetVideoSourceModeResponse",
            callback
        );
    }

    /**
     * @brief GetOSDs operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetOSDs(const tr2_GetOSDs& request,
                           const OnvifCallback<tr2_GetOSDsResponse>& callback) {
        call_service<tr2_GetOSDs, tr2_GetOSDsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetOSDs",
            request,
            "GetOSDs",
            "GetOSDsResponse",
            callback
        );
    }

    /**
     * @brief GetOSDOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetOSDOptions(const tr2_GetOSDOptions& request,
                           const OnvifCallback<tr2_GetOSDOptionsResponse>& callback) {
        call_service<tr2_GetOSDOptions, tr2_GetOSDOptionsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetOSDOptions",
            request,
            "GetOSDOptions",
            "GetOSDOptionsResponse",
            callback
        );
    }

    /**
     * @brief SetOSD operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetOSD(const tr2_SetOSD& request,
                           const OnvifCallback<tr2_SetOSDResponse>& callback) {
        call_service<tr2_SetOSD, tr2_SetOSDResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetOSD",
            request,
            "SetOSD",
            "SetOSDResponse",
            callback
        );
    }

    /**
     * @brief CreateOSD operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateOSD(const tr2_CreateOSD& request,
                           const OnvifCallback<tr2_CreateOSDResponse>& callback) {
        call_service<tr2_CreateOSD, tr2_CreateOSDResponse>(
            "http://www.onvif.org/ver20/media/wsdl/CreateOSD",
            request,
            "CreateOSD",
            "CreateOSDResponse",
            callback
        );
    }

    /**
     * @brief DeleteOSD operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteOSD(const tr2_DeleteOSD& request,
                           const OnvifCallback<tr2_DeleteOSDResponse>& callback) {
        call_service<tr2_DeleteOSD, tr2_DeleteOSDResponse>(
            "http://www.onvif.org/ver20/media/wsdl/DeleteOSD",
            request,
            "DeleteOSD",
            "DeleteOSDResponse",
            callback
        );
    }

    /**
     * @brief GetMasks operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetMasks(const tr2_GetMasks& request,
                           const OnvifCallback<tr2_GetMasksResponse>& callback) {
        call_service<tr2_GetMasks, tr2_GetMasksResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetMasks",
            request,
            "GetMasks",
            "GetMasksResponse",
            callback
        );
    }

    /**
     * @brief GetMaskOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetMaskOptions(const tr2_GetMaskOptions& request,
                           const OnvifCallback<tr2_GetMaskOptionsResponse>& callback) {
        call_service<tr2_GetMaskOptions, tr2_GetMaskOptionsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetMaskOptions",
            request,
            "GetMaskOptions",
            "GetMaskOptionsResponse",
            callback
        );
    }

    /**
     * @brief SetMask operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetMask(const tr2_SetMask& request,
                           const OnvifCallback<tr2_SetMaskResponse>& callback) {
        call_service<tr2_SetMask, tr2_SetMaskResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetMask",
            request,
            "SetMask",
            "SetMaskResponse",
            callback
        );
    }

    /**
     * @brief CreateMask operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateMask(const tr2_CreateMask& request,
                           const OnvifCallback<tr2_CreateMaskResponse>& callback) {
        call_service<tr2_CreateMask, tr2_CreateMaskResponse>(
            "http://www.onvif.org/ver20/media/wsdl/CreateMask",
            request,
            "CreateMask",
            "CreateMaskResponse",
            callback
        );
    }

    /**
     * @brief DeleteMask operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteMask(const tr2_DeleteMask& request,
                           const OnvifCallback<tr2_DeleteMaskResponse>& callback) {
        call_service<tr2_DeleteMask, tr2_DeleteMaskResponse>(
            "http://www.onvif.org/ver20/media/wsdl/DeleteMask",
            request,
            "DeleteMask",
            "DeleteMaskResponse",
            callback
        );
    }

    /**
     * @brief GetWebRTCConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetWebRTCConfigurations(const tr2_GetWebRTCConfigurations& request,
                           const OnvifCallback<tr2_GetWebRTCConfigurationsResponse>& callback) {
        call_service<tr2_GetWebRTCConfigurations, tr2_GetWebRTCConfigurationsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetWebRTCConfigurations",
            request,
            "GetWebRTCConfigurations",
            "GetWebRTCConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief SetWebRTCConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetWebRTCConfigurations(const tr2_SetWebRTCConfigurations& request,
                           const OnvifCallback<tr2_SetWebRTCConfigurationsResponse>& callback) {
        call_service<tr2_SetWebRTCConfigurations, tr2_SetWebRTCConfigurationsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetWebRTCConfigurations",
            request,
            "SetWebRTCConfigurations",
            "SetWebRTCConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioClips operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioClips(const tr2_GetAudioClips& request,
                           const OnvifCallback<tr2_GetAudioClipsResponse>& callback) {
        call_service<tr2_GetAudioClips, tr2_GetAudioClipsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetAudioClips",
            request,
            "GetAudioClips",
            "GetAudioClipsResponse",
            callback
        );
    }

    /**
     * @brief AddAudioClip operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddAudioClip(const tr2_AddAudioClip& request,
                           const OnvifCallback<tr2_AddAudioClipResponse>& callback) {
        call_service<tr2_AddAudioClip, tr2_AddAudioClipResponse>(
            "http://www.onvif.org/ver20/media/wsdl/AddAudioClip",
            request,
            "AddAudioClip",
            "AddAudioClipResponse",
            callback
        );
    }

    /**
     * @brief SetAudioClip operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetAudioClip(const tr2_SetAudioClip& request,
                           const OnvifCallback<tr2_SetAudioClipResponse>& callback) {
        call_service<tr2_SetAudioClip, tr2_SetAudioClipResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetAudioClip",
            request,
            "SetAudioClip",
            "SetAudioClipResponse",
            callback
        );
    }

    /**
     * @brief DeleteAudioClip operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteAudioClip(const tr2_DeleteAudioClip& request,
                           const OnvifCallback<tr2_DeleteAudioClipResponse>& callback) {
        call_service<tr2_DeleteAudioClip, tr2_DeleteAudioClipResponse>(
            "http://www.onvif.org/ver20/media/wsdl/DeleteAudioClip",
            request,
            "DeleteAudioClip",
            "DeleteAudioClipResponse",
            callback
        );
    }

    /**
     * @brief PlayAudioClip operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void PlayAudioClip(const tr2_PlayAudioClip& request,
                           const OnvifCallback<tr2_PlayAudioClipResponse>& callback) {
        call_service<tr2_PlayAudioClip, tr2_PlayAudioClipResponse>(
            "http://www.onvif.org/ver20/media/wsdl/PlayAudioClip",
            request,
            "PlayAudioClip",
            "PlayAudioClipResponse",
            callback
        );
    }

    /**
     * @brief GetPlayingAudioClips operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetPlayingAudioClips(const tr2_GetPlayingAudioClips& request,
                           const OnvifCallback<tr2_GetPlayingAudioClipsResponse>& callback) {
        call_service<tr2_GetPlayingAudioClips, tr2_GetPlayingAudioClipsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetPlayingAudioClips",
            request,
            "GetPlayingAudioClips",
            "GetPlayingAudioClipsResponse",
            callback
        );
    }

    /**
     * @brief GetMulticastAudioDecoderConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetMulticastAudioDecoderConfigurations(const tr2_GetMulticastAudioDecoderConfigurations& request,
                           const OnvifCallback<tr2_GetMulticastAudioDecoderConfigurationsResponse>& callback) {
        call_service<tr2_GetMulticastAudioDecoderConfigurations, tr2_GetMulticastAudioDecoderConfigurationsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetMulticastAudioDecoderConfigurations",
            request,
            "GetMulticastAudioDecoderConfigurations",
            "GetMulticastAudioDecoderConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetMulticastAudioDecoderConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetMulticastAudioDecoderConfigurationOptions(const tr2_GetMulticastAudioDecoderConfigurationOptions& request,
                           const OnvifCallback<tr2_GetMulticastAudioDecoderConfigurationOptionsResponse>& callback) {
        call_service<tr2_GetMulticastAudioDecoderConfigurationOptions, tr2_GetMulticastAudioDecoderConfigurationOptionsResponse>(
            "http://www.onvif.org/ver20/media/wsdl/GetMulticastAudioDecoderConfigurationOptions",
            request,
            "GetMulticastAudioDecoderConfigurationOptions",
            "GetMulticastAudioDecoderConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief SetMulticastAudioDecoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetMulticastAudioDecoderConfiguration(const tr2_SetMulticastAudioDecoderConfiguration& request,
                           const OnvifCallback<tr2_SetMulticastAudioDecoderConfigurationResponse>& callback) {
        call_service<tr2_SetMulticastAudioDecoderConfiguration, tr2_SetMulticastAudioDecoderConfigurationResponse>(
            "http://www.onvif.org/ver20/media/wsdl/SetMulticastAudioDecoderConfiguration",
            request,
            "SetMulticastAudioDecoderConfiguration",
            "SetMulticastAudioDecoderConfigurationResponse",
            callback
        );
    }

    const char *get_namespace_prefix() const override {
        return TARGET_NAMESPACE_PREFIX;
    }

    const char *get_namespace_uri() const override {
        return TARGET_NAMESPACE;
    }

    static constexpr const char* TARGET_NAMESPACE = "http://www.onvif.org/ver20/media/wsdl";
    static constexpr const char* TARGET_NAMESPACE_PREFIX = "tr2";
};

} // namespace libonvif_client
