/**
 * @file MediaClient.h
 * @brief MediaService client (header-only)
 * @note This file is auto-generated by wsdl_parser2, do not modify manually
 */

#pragma once

#include <libonvif_client/core/onvif_service_base.h>
#include <libonvif_client/core/onvif_callback.h>
#include <libonvif_client/types/trt.h>

namespace libonvif_client {

/**
 * @brief MediaService client
 * @namespace http://www.onvif.org/ver10/media/wsdl
 */
class MediaClient : public OnvifServiceBase {
public:
    /**
     * @brief Constructor
     * @param service_url ONVIF service endpoint URL
     * @param http_client HTTP client implementation (user provided)
     * @param username Authentication username (optional)
     * @param password Authentication password (optional)
     */
    MediaClient(const std::string& service_url,
                    const std::shared_ptr<IHttpClient>& http_client,
                    const std::string& username = "",
                    const std::string& password = "")
        : OnvifServiceBase(service_url, http_client, username, password) {
    }

    /**
     * @brief GetServiceCapabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetServiceCapabilities(const trt_GetServiceCapabilities& request,
                           const OnvifCallback<trt_GetServiceCapabilitiesResponse>& callback) {
        call_service<trt_GetServiceCapabilities, trt_GetServiceCapabilitiesResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetServiceCapabilities",
            request,
            "GetServiceCapabilities",
            "GetServiceCapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief GetVideoSources operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoSources(const trt_GetVideoSources& request,
                           const OnvifCallback<trt_GetVideoSourcesResponse>& callback) {
        call_service<trt_GetVideoSources, trt_GetVideoSourcesResponse>(
            "http://www.onvif.org/ver10/media/wsdlGetVideoSources/",
            request,
            "GetVideoSources",
            "GetVideoSourcesResponse",
            callback
        );
    }

    /**
     * @brief GetAudioSources operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioSources(const trt_GetAudioSources& request,
                           const OnvifCallback<trt_GetAudioSourcesResponse>& callback) {
        call_service<trt_GetAudioSources, trt_GetAudioSourcesResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetAudioSources",
            request,
            "GetAudioSources",
            "GetAudioSourcesResponse",
            callback
        );
    }

    /**
     * @brief GetAudioOutputs operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioOutputs(const trt_GetAudioOutputs& request,
                           const OnvifCallback<trt_GetAudioOutputsResponse>& callback) {
        call_service<trt_GetAudioOutputs, trt_GetAudioOutputsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetAudioOutputs",
            request,
            "GetAudioOutputs",
            "GetAudioOutputsResponse",
            callback
        );
    }

    /**
     * @brief CreateProfile operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateProfile(const trt_CreateProfile& request,
                           const OnvifCallback<trt_CreateProfileResponse>& callback) {
        call_service<trt_CreateProfile, trt_CreateProfileResponse>(
            "http://www.onvif.org/ver10/media/wsdl/CreateProfile",
            request,
            "CreateProfile",
            "CreateProfileResponse",
            callback
        );
    }

    /**
     * @brief GetProfile operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetProfile(const trt_GetProfile& request,
                           const OnvifCallback<trt_GetProfileResponse>& callback) {
        call_service<trt_GetProfile, trt_GetProfileResponse>(
            "http://www.onvif.org/ver10/media/wsdlGetProfile/",
            request,
            "GetProfile",
            "GetProfileResponse",
            callback
        );
    }

    /**
     * @brief GetProfiles operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetProfiles(const trt_GetProfiles& request,
                           const OnvifCallback<trt_GetProfilesResponse>& callback) {
        call_service<trt_GetProfiles, trt_GetProfilesResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetProfiles",
            request,
            "GetProfiles",
            "GetProfilesResponse",
            callback
        );
    }

    /**
     * @brief AddVideoEncoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddVideoEncoderConfiguration(const trt_AddVideoEncoderConfiguration& request,
                           const OnvifCallback<trt_AddVideoEncoderConfigurationResponse>& callback) {
        call_service<trt_AddVideoEncoderConfiguration, trt_AddVideoEncoderConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/AddVideoEncoderConfiguration",
            request,
            "AddVideoEncoderConfiguration",
            "AddVideoEncoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief RemoveVideoEncoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemoveVideoEncoderConfiguration(const trt_RemoveVideoEncoderConfiguration& request,
                           const OnvifCallback<trt_RemoveVideoEncoderConfigurationResponse>& callback) {
        call_service<trt_RemoveVideoEncoderConfiguration, trt_RemoveVideoEncoderConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/RemoveVideoEncoderConfiguration",
            request,
            "RemoveVideoEncoderConfiguration",
            "RemoveVideoEncoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief AddVideoSourceConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddVideoSourceConfiguration(const trt_AddVideoSourceConfiguration& request,
                           const OnvifCallback<trt_AddVideoSourceConfigurationResponse>& callback) {
        call_service<trt_AddVideoSourceConfiguration, trt_AddVideoSourceConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/AddVideoSourceConfiguration",
            request,
            "AddVideoSourceConfiguration",
            "AddVideoSourceConfigurationResponse",
            callback
        );
    }

    /**
     * @brief RemoveVideoSourceConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemoveVideoSourceConfiguration(const trt_RemoveVideoSourceConfiguration& request,
                           const OnvifCallback<trt_RemoveVideoSourceConfigurationResponse>& callback) {
        call_service<trt_RemoveVideoSourceConfiguration, trt_RemoveVideoSourceConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/RemoveVideoSourceConfiguration",
            request,
            "RemoveVideoSourceConfiguration",
            "RemoveVideoSourceConfigurationResponse",
            callback
        );
    }

    /**
     * @brief AddAudioEncoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddAudioEncoderConfiguration(const trt_AddAudioEncoderConfiguration& request,
                           const OnvifCallback<trt_AddAudioEncoderConfigurationResponse>& callback) {
        call_service<trt_AddAudioEncoderConfiguration, trt_AddAudioEncoderConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/AddAudioEncoderConfiguration",
            request,
            "AddAudioEncoderConfiguration",
            "AddAudioEncoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief RemoveAudioEncoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemoveAudioEncoderConfiguration(const trt_RemoveAudioEncoderConfiguration& request,
                           const OnvifCallback<trt_RemoveAudioEncoderConfigurationResponse>& callback) {
        call_service<trt_RemoveAudioEncoderConfiguration, trt_RemoveAudioEncoderConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/RemoveAudioEncoderConfiguration",
            request,
            "RemoveAudioEncoderConfiguration",
            "RemoveAudioEncoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief AddAudioSourceConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddAudioSourceConfiguration(const trt_AddAudioSourceConfiguration& request,
                           const OnvifCallback<trt_AddAudioSourceConfigurationResponse>& callback) {
        call_service<trt_AddAudioSourceConfiguration, trt_AddAudioSourceConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/AddAudioSourceConfiguration",
            request,
            "AddAudioSourceConfiguration",
            "AddAudioSourceConfigurationResponse",
            callback
        );
    }

    /**
     * @brief RemoveAudioSourceConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemoveAudioSourceConfiguration(const trt_RemoveAudioSourceConfiguration& request,
                           const OnvifCallback<trt_RemoveAudioSourceConfigurationResponse>& callback) {
        call_service<trt_RemoveAudioSourceConfiguration, trt_RemoveAudioSourceConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/RemoveAudioSourceConfiguration",
            request,
            "RemoveAudioSourceConfiguration",
            "RemoveAudioSourceConfigurationResponse",
            callback
        );
    }

    /**
     * @brief AddPTZConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddPTZConfiguration(const trt_AddPTZConfiguration& request,
                           const OnvifCallback<trt_AddPTZConfigurationResponse>& callback) {
        call_service<trt_AddPTZConfiguration, trt_AddPTZConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/AddPTZConfiguration",
            request,
            "AddPTZConfiguration",
            "AddPTZConfigurationResponse",
            callback
        );
    }

    /**
     * @brief RemovePTZConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemovePTZConfiguration(const trt_RemovePTZConfiguration& request,
                           const OnvifCallback<trt_RemovePTZConfigurationResponse>& callback) {
        call_service<trt_RemovePTZConfiguration, trt_RemovePTZConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/RemovePTZConfiguration",
            request,
            "RemovePTZConfiguration",
            "RemovePTZConfigurationResponse",
            callback
        );
    }

    /**
     * @brief AddVideoAnalyticsConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddVideoAnalyticsConfiguration(const trt_AddVideoAnalyticsConfiguration& request,
                           const OnvifCallback<trt_AddVideoAnalyticsConfigurationResponse>& callback) {
        call_service<trt_AddVideoAnalyticsConfiguration, trt_AddVideoAnalyticsConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/AddVideoAnalyticsConfiguration",
            request,
            "AddVideoAnalyticsConfiguration",
            "AddVideoAnalyticsConfigurationResponse",
            callback
        );
    }

    /**
     * @brief RemoveVideoAnalyticsConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemoveVideoAnalyticsConfiguration(const trt_RemoveVideoAnalyticsConfiguration& request,
                           const OnvifCallback<trt_RemoveVideoAnalyticsConfigurationResponse>& callback) {
        call_service<trt_RemoveVideoAnalyticsConfiguration, trt_RemoveVideoAnalyticsConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/RemoveVideoAnalyticsConfiguration",
            request,
            "RemoveVideoAnalyticsConfiguration",
            "RemoveVideoAnalyticsConfigurationResponse",
            callback
        );
    }

    /**
     * @brief AddMetadataConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddMetadataConfiguration(const trt_AddMetadataConfiguration& request,
                           const OnvifCallback<trt_AddMetadataConfigurationResponse>& callback) {
        call_service<trt_AddMetadataConfiguration, trt_AddMetadataConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/AddMetadataConfiguration",
            request,
            "AddMetadataConfiguration",
            "AddMetadataConfigurationResponse",
            callback
        );
    }

    /**
     * @brief RemoveMetadataConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemoveMetadataConfiguration(const trt_RemoveMetadataConfiguration& request,
                           const OnvifCallback<trt_RemoveMetadataConfigurationResponse>& callback) {
        call_service<trt_RemoveMetadataConfiguration, trt_RemoveMetadataConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/RemoveMetadataConfiguration",
            request,
            "RemoveMetadataConfiguration",
            "RemoveMetadataConfigurationResponse",
            callback
        );
    }

    /**
     * @brief AddAudioOutputConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddAudioOutputConfiguration(const trt_AddAudioOutputConfiguration& request,
                           const OnvifCallback<trt_AddAudioOutputConfigurationResponse>& callback) {
        call_service<trt_AddAudioOutputConfiguration, trt_AddAudioOutputConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/AddAudioOutputConfiguration",
            request,
            "AddAudioOutputConfiguration",
            "AddAudioOutputConfigurationResponse",
            callback
        );
    }

    /**
     * @brief RemoveAudioOutputConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemoveAudioOutputConfiguration(const trt_RemoveAudioOutputConfiguration& request,
                           const OnvifCallback<trt_RemoveAudioOutputConfigurationResponse>& callback) {
        call_service<trt_RemoveAudioOutputConfiguration, trt_RemoveAudioOutputConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/RemoveAudioOutputConfiguration",
            request,
            "RemoveAudioOutputConfiguration",
            "RemoveAudioOutputConfigurationResponse",
            callback
        );
    }

    /**
     * @brief AddAudioDecoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AddAudioDecoderConfiguration(const trt_AddAudioDecoderConfiguration& request,
                           const OnvifCallback<trt_AddAudioDecoderConfigurationResponse>& callback) {
        call_service<trt_AddAudioDecoderConfiguration, trt_AddAudioDecoderConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/AddAudioDecoderConfiguration",
            request,
            "AddAudioDecoderConfiguration",
            "AddAudioDecoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief RemoveAudioDecoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemoveAudioDecoderConfiguration(const trt_RemoveAudioDecoderConfiguration& request,
                           const OnvifCallback<trt_RemoveAudioDecoderConfigurationResponse>& callback) {
        call_service<trt_RemoveAudioDecoderConfiguration, trt_RemoveAudioDecoderConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/RemoveAudioDecoderConfiguration",
            request,
            "RemoveAudioDecoderConfiguration",
            "RemoveAudioDecoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief DeleteProfile operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteProfile(const trt_DeleteProfile& request,
                           const OnvifCallback<trt_DeleteProfileResponse>& callback) {
        call_service<trt_DeleteProfile, trt_DeleteProfileResponse>(
            "http://www.onvif.org/ver10/media/wsdl/DeleteProfile",
            request,
            "DeleteProfile",
            "DeleteProfileResponse",
            callback
        );
    }

    /**
     * @brief GetVideoSourceConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoSourceConfigurations(const trt_GetVideoSourceConfigurations& request,
                           const OnvifCallback<trt_GetVideoSourceConfigurationsResponse>& callback) {
        call_service<trt_GetVideoSourceConfigurations, trt_GetVideoSourceConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetVideoSourceConfigurations",
            request,
            "GetVideoSourceConfigurations",
            "GetVideoSourceConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetVideoEncoderConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoEncoderConfigurations(const trt_GetVideoEncoderConfigurations& request,
                           const OnvifCallback<trt_GetVideoEncoderConfigurationsResponse>& callback) {
        call_service<trt_GetVideoEncoderConfigurations, trt_GetVideoEncoderConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetVideoEncoderConfigurations",
            request,
            "GetVideoEncoderConfigurations",
            "GetVideoEncoderConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioSourceConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioSourceConfigurations(const trt_GetAudioSourceConfigurations& request,
                           const OnvifCallback<trt_GetAudioSourceConfigurationsResponse>& callback) {
        call_service<trt_GetAudioSourceConfigurations, trt_GetAudioSourceConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdlGetAudioSourceConfigurations/",
            request,
            "GetAudioSourceConfigurations",
            "GetAudioSourceConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioEncoderConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioEncoderConfigurations(const trt_GetAudioEncoderConfigurations& request,
                           const OnvifCallback<trt_GetAudioEncoderConfigurationsResponse>& callback) {
        call_service<trt_GetAudioEncoderConfigurations, trt_GetAudioEncoderConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetAudioEncoderConfigurations",
            request,
            "GetAudioEncoderConfigurations",
            "GetAudioEncoderConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetVideoAnalyticsConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoAnalyticsConfigurations(const trt_GetVideoAnalyticsConfigurations& request,
                           const OnvifCallback<trt_GetVideoAnalyticsConfigurationsResponse>& callback) {
        call_service<trt_GetVideoAnalyticsConfigurations, trt_GetVideoAnalyticsConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetVideoAnalyticsConfigurations",
            request,
            "GetVideoAnalyticsConfigurations",
            "GetVideoAnalyticsConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetMetadataConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetMetadataConfigurations(const trt_GetMetadataConfigurations& request,
                           const OnvifCallback<trt_GetMetadataConfigurationsResponse>& callback) {
        call_service<trt_GetMetadataConfigurations, trt_GetMetadataConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetMetadataConfigurations",
            request,
            "GetMetadataConfigurations",
            "GetMetadataConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioOutputConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioOutputConfigurations(const trt_GetAudioOutputConfigurations& request,
                           const OnvifCallback<trt_GetAudioOutputConfigurationsResponse>& callback) {
        call_service<trt_GetAudioOutputConfigurations, trt_GetAudioOutputConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetAudioOutputConfigurations",
            request,
            "GetAudioOutputConfigurations",
            "GetAudioOutputConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioDecoderConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioDecoderConfigurations(const trt_GetAudioDecoderConfigurations& request,
                           const OnvifCallback<trt_GetAudioDecoderConfigurationsResponse>& callback) {
        call_service<trt_GetAudioDecoderConfigurations, trt_GetAudioDecoderConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetAudioDecoderConfigurations",
            request,
            "GetAudioDecoderConfigurations",
            "GetAudioDecoderConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetVideoSourceConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoSourceConfiguration(const trt_GetVideoSourceConfiguration& request,
                           const OnvifCallback<trt_GetVideoSourceConfigurationResponse>& callback) {
        call_service<trt_GetVideoSourceConfiguration, trt_GetVideoSourceConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetVideoSourceConfiguration",
            request,
            "GetVideoSourceConfiguration",
            "GetVideoSourceConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetVideoEncoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoEncoderConfiguration(const trt_GetVideoEncoderConfiguration& request,
                           const OnvifCallback<trt_GetVideoEncoderConfigurationResponse>& callback) {
        call_service<trt_GetVideoEncoderConfiguration, trt_GetVideoEncoderConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetVideoEncoderConfiguration",
            request,
            "GetVideoEncoderConfiguration",
            "GetVideoEncoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetAudioSourceConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioSourceConfiguration(const trt_GetAudioSourceConfiguration& request,
                           const OnvifCallback<trt_GetAudioSourceConfigurationResponse>& callback) {
        call_service<trt_GetAudioSourceConfiguration, trt_GetAudioSourceConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetAudioSourceConfiguration",
            request,
            "GetAudioSourceConfiguration",
            "GetAudioSourceConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetAudioEncoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioEncoderConfiguration(const trt_GetAudioEncoderConfiguration& request,
                           const OnvifCallback<trt_GetAudioEncoderConfigurationResponse>& callback) {
        call_service<trt_GetAudioEncoderConfiguration, trt_GetAudioEncoderConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetAudioEncoderConfiguration",
            request,
            "GetAudioEncoderConfiguration",
            "GetAudioEncoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetVideoAnalyticsConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoAnalyticsConfiguration(const trt_GetVideoAnalyticsConfiguration& request,
                           const OnvifCallback<trt_GetVideoAnalyticsConfigurationResponse>& callback) {
        call_service<trt_GetVideoAnalyticsConfiguration, trt_GetVideoAnalyticsConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetVideoAnalyticsConfiguration",
            request,
            "GetVideoAnalyticsConfiguration",
            "GetVideoAnalyticsConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetMetadataConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetMetadataConfiguration(const trt_GetMetadataConfiguration& request,
                           const OnvifCallback<trt_GetMetadataConfigurationResponse>& callback) {
        call_service<trt_GetMetadataConfiguration, trt_GetMetadataConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetMetadataConfiguration",
            request,
            "GetMetadataConfiguration",
            "GetMetadataConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetAudioOutputConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioOutputConfiguration(const trt_GetAudioOutputConfiguration& request,
                           const OnvifCallback<trt_GetAudioOutputConfigurationResponse>& callback) {
        call_service<trt_GetAudioOutputConfiguration, trt_GetAudioOutputConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetAudioOutputConfiguration",
            request,
            "GetAudioOutputConfiguration",
            "GetAudioOutputConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetAudioDecoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioDecoderConfiguration(const trt_GetAudioDecoderConfiguration& request,
                           const OnvifCallback<trt_GetAudioDecoderConfigurationResponse>& callback) {
        call_service<trt_GetAudioDecoderConfiguration, trt_GetAudioDecoderConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetAudioDecoderConfiguration",
            request,
            "GetAudioDecoderConfiguration",
            "GetAudioDecoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetCompatibleVideoEncoderConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCompatibleVideoEncoderConfigurations(const trt_GetCompatibleVideoEncoderConfigurations& request,
                           const OnvifCallback<trt_GetCompatibleVideoEncoderConfigurationsResponse>& callback) {
        call_service<trt_GetCompatibleVideoEncoderConfigurations, trt_GetCompatibleVideoEncoderConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetCompatibleVideoEncoderConfigurations",
            request,
            "GetCompatibleVideoEncoderConfigurations",
            "GetCompatibleVideoEncoderConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetCompatibleVideoSourceConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCompatibleVideoSourceConfigurations(const trt_GetCompatibleVideoSourceConfigurations& request,
                           const OnvifCallback<trt_GetCompatibleVideoSourceConfigurationsResponse>& callback) {
        call_service<trt_GetCompatibleVideoSourceConfigurations, trt_GetCompatibleVideoSourceConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetCompatibleVideoSourceConfigurations",
            request,
            "GetCompatibleVideoSourceConfigurations",
            "GetCompatibleVideoSourceConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetCompatibleAudioEncoderConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCompatibleAudioEncoderConfigurations(const trt_GetCompatibleAudioEncoderConfigurations& request,
                           const OnvifCallback<trt_GetCompatibleAudioEncoderConfigurationsResponse>& callback) {
        call_service<trt_GetCompatibleAudioEncoderConfigurations, trt_GetCompatibleAudioEncoderConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetCompatibleAudioEncoderConfigurations",
            request,
            "GetCompatibleAudioEncoderConfigurations",
            "GetCompatibleAudioEncoderConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetCompatibleAudioSourceConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCompatibleAudioSourceConfigurations(const trt_GetCompatibleAudioSourceConfigurations& request,
                           const OnvifCallback<trt_GetCompatibleAudioSourceConfigurationsResponse>& callback) {
        call_service<trt_GetCompatibleAudioSourceConfigurations, trt_GetCompatibleAudioSourceConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetCompatibleAudioSourceConfigurations",
            request,
            "GetCompatibleAudioSourceConfigurations",
            "GetCompatibleAudioSourceConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetCompatibleVideoAnalyticsConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCompatibleVideoAnalyticsConfigurations(const trt_GetCompatibleVideoAnalyticsConfigurations& request,
                           const OnvifCallback<trt_GetCompatibleVideoAnalyticsConfigurationsResponse>& callback) {
        call_service<trt_GetCompatibleVideoAnalyticsConfigurations, trt_GetCompatibleVideoAnalyticsConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetCompatibleVideoAnalyticsConfigurations",
            request,
            "GetCompatibleVideoAnalyticsConfigurations",
            "GetCompatibleVideoAnalyticsConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetCompatibleMetadataConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCompatibleMetadataConfigurations(const trt_GetCompatibleMetadataConfigurations& request,
                           const OnvifCallback<trt_GetCompatibleMetadataConfigurationsResponse>& callback) {
        call_service<trt_GetCompatibleMetadataConfigurations, trt_GetCompatibleMetadataConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetCompatibleMetadataConfigurations",
            request,
            "GetCompatibleMetadataConfigurations",
            "GetCompatibleMetadataConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetCompatibleAudioOutputConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCompatibleAudioOutputConfigurations(const trt_GetCompatibleAudioOutputConfigurations& request,
                           const OnvifCallback<trt_GetCompatibleAudioOutputConfigurationsResponse>& callback) {
        call_service<trt_GetCompatibleAudioOutputConfigurations, trt_GetCompatibleAudioOutputConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetCompatibleAudioOutputConfigurations",
            request,
            "GetCompatibleAudioOutputConfigurations",
            "GetCompatibleAudioOutputConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief GetCompatibleAudioDecoderConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCompatibleAudioDecoderConfigurations(const trt_GetCompatibleAudioDecoderConfigurations& request,
                           const OnvifCallback<trt_GetCompatibleAudioDecoderConfigurationsResponse>& callback) {
        call_service<trt_GetCompatibleAudioDecoderConfigurations, trt_GetCompatibleAudioDecoderConfigurationsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetCompatibleAudioDecoderConfigurations",
            request,
            "GetCompatibleAudioDecoderConfigurations",
            "GetCompatibleAudioDecoderConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief SetVideoSourceConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetVideoSourceConfiguration(const trt_SetVideoSourceConfiguration& request,
                           const OnvifCallback<trt_SetVideoSourceConfigurationResponse>& callback) {
        call_service<trt_SetVideoSourceConfiguration, trt_SetVideoSourceConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/SetVideoSourceConfiguration",
            request,
            "SetVideoSourceConfiguration",
            "SetVideoSourceConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetVideoEncoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetVideoEncoderConfiguration(const trt_SetVideoEncoderConfiguration& request,
                           const OnvifCallback<trt_SetVideoEncoderConfigurationResponse>& callback) {
        call_service<trt_SetVideoEncoderConfiguration, trt_SetVideoEncoderConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/SetVideoEncoderConfiguration",
            request,
            "SetVideoEncoderConfiguration",
            "SetVideoEncoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetAudioSourceConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetAudioSourceConfiguration(const trt_SetAudioSourceConfiguration& request,
                           const OnvifCallback<trt_SetAudioSourceConfigurationResponse>& callback) {
        call_service<trt_SetAudioSourceConfiguration, trt_SetAudioSourceConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/SetAudioSourceConfiguration",
            request,
            "SetAudioSourceConfiguration",
            "SetAudioSourceConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetAudioEncoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetAudioEncoderConfiguration(const trt_SetAudioEncoderConfiguration& request,
                           const OnvifCallback<trt_SetAudioEncoderConfigurationResponse>& callback) {
        call_service<trt_SetAudioEncoderConfiguration, trt_SetAudioEncoderConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/SetAudioEncoderConfiguration",
            request,
            "SetAudioEncoderConfiguration",
            "SetAudioEncoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetVideoAnalyticsConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetVideoAnalyticsConfiguration(const trt_SetVideoAnalyticsConfiguration& request,
                           const OnvifCallback<trt_SetVideoAnalyticsConfigurationResponse>& callback) {
        call_service<trt_SetVideoAnalyticsConfiguration, trt_SetVideoAnalyticsConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/SetVideoAnalyticsConfiguration",
            request,
            "SetVideoAnalyticsConfiguration",
            "SetVideoAnalyticsConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetMetadataConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetMetadataConfiguration(const trt_SetMetadataConfiguration& request,
                           const OnvifCallback<trt_SetMetadataConfigurationResponse>& callback) {
        call_service<trt_SetMetadataConfiguration, trt_SetMetadataConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/SetMetadataConfiguration",
            request,
            "SetMetadataConfiguration",
            "SetMetadataConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetAudioOutputConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetAudioOutputConfiguration(const trt_SetAudioOutputConfiguration& request,
                           const OnvifCallback<trt_SetAudioOutputConfigurationResponse>& callback) {
        call_service<trt_SetAudioOutputConfiguration, trt_SetAudioOutputConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/SetAudioOutputConfiguration",
            request,
            "SetAudioOutputConfiguration",
            "SetAudioOutputConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetAudioDecoderConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetAudioDecoderConfiguration(const trt_SetAudioDecoderConfiguration& request,
                           const OnvifCallback<trt_SetAudioDecoderConfigurationResponse>& callback) {
        call_service<trt_SetAudioDecoderConfiguration, trt_SetAudioDecoderConfigurationResponse>(
            "http://www.onvif.org/ver10/media/wsdl/SetAudioDecoderConfiguration",
            request,
            "SetAudioDecoderConfiguration",
            "SetAudioDecoderConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetVideoSourceConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoSourceConfigurationOptions(const trt_GetVideoSourceConfigurationOptions& request,
                           const OnvifCallback<trt_GetVideoSourceConfigurationOptionsResponse>& callback) {
        call_service<trt_GetVideoSourceConfigurationOptions, trt_GetVideoSourceConfigurationOptionsResponse>(
            "http://www.onvif.org/ver10/media/wsdlGetVideoSourceConfigurationOptions/",
            request,
            "GetVideoSourceConfigurationOptions",
            "GetVideoSourceConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetVideoEncoderConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoEncoderConfigurationOptions(const trt_GetVideoEncoderConfigurationOptions& request,
                           const OnvifCallback<trt_GetVideoEncoderConfigurationOptionsResponse>& callback) {
        call_service<trt_GetVideoEncoderConfigurationOptions, trt_GetVideoEncoderConfigurationOptionsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetVideoEncoderConfigurationOptions",
            request,
            "GetVideoEncoderConfigurationOptions",
            "GetVideoEncoderConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioSourceConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioSourceConfigurationOptions(const trt_GetAudioSourceConfigurationOptions& request,
                           const OnvifCallback<trt_GetAudioSourceConfigurationOptionsResponse>& callback) {
        call_service<trt_GetAudioSourceConfigurationOptions, trt_GetAudioSourceConfigurationOptionsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetAudioSourceConfigurationOptions",
            request,
            "GetAudioSourceConfigurationOptions",
            "GetAudioSourceConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioEncoderConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioEncoderConfigurationOptions(const trt_GetAudioEncoderConfigurationOptions& request,
                           const OnvifCallback<trt_GetAudioEncoderConfigurationOptionsResponse>& callback) {
        call_service<trt_GetAudioEncoderConfigurationOptions, trt_GetAudioEncoderConfigurationOptionsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetAudioEncoderConfigurationOptions",
            request,
            "GetAudioEncoderConfigurationOptions",
            "GetAudioEncoderConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetMetadataConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetMetadataConfigurationOptions(const trt_GetMetadataConfigurationOptions& request,
                           const OnvifCallback<trt_GetMetadataConfigurationOptionsResponse>& callback) {
        call_service<trt_GetMetadataConfigurationOptions, trt_GetMetadataConfigurationOptionsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetMetadataConfigurationOptions",
            request,
            "GetMetadataConfigurationOptions",
            "GetMetadataConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioOutputConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioOutputConfigurationOptions(const trt_GetAudioOutputConfigurationOptions& request,
                           const OnvifCallback<trt_GetAudioOutputConfigurationOptionsResponse>& callback) {
        call_service<trt_GetAudioOutputConfigurationOptions, trt_GetAudioOutputConfigurationOptionsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetAudioOutputConfigurationOptions",
            request,
            "GetAudioOutputConfigurationOptions",
            "GetAudioOutputConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetAudioDecoderConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAudioDecoderConfigurationOptions(const trt_GetAudioDecoderConfigurationOptions& request,
                           const OnvifCallback<trt_GetAudioDecoderConfigurationOptionsResponse>& callback) {
        call_service<trt_GetAudioDecoderConfigurationOptions, trt_GetAudioDecoderConfigurationOptionsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetAudioDecoderConfigurationOptions",
            request,
            "GetAudioDecoderConfigurationOptions",
            "GetAudioDecoderConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief GetGuaranteedNumberOfVideoEncoderInstances operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetGuaranteedNumberOfVideoEncoderInstances(const trt_GetGuaranteedNumberOfVideoEncoderInstances& request,
                           const OnvifCallback<trt_GetGuaranteedNumberOfVideoEncoderInstancesResponse>& callback) {
        call_service<trt_GetGuaranteedNumberOfVideoEncoderInstances, trt_GetGuaranteedNumberOfVideoEncoderInstancesResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetGuaranteedNumberOfVideoEncoderInstances",
            request,
            "GetGuaranteedNumberOfVideoEncoderInstances",
            "GetGuaranteedNumberOfVideoEncoderInstancesResponse",
            callback
        );
    }

    /**
     * @brief GetStreamUri operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetStreamUri(const trt_GetStreamUri& request,
                           const OnvifCallback<trt_GetStreamUriResponse>& callback) {
        call_service<trt_GetStreamUri, trt_GetStreamUriResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetStreamUri",
            request,
            "GetStreamUri",
            "GetStreamUriResponse",
            callback
        );
    }

    /**
     * @brief StartMulticastStreaming operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void StartMulticastStreaming(const trt_StartMulticastStreaming& request,
                           const OnvifCallback<trt_StartMulticastStreamingResponse>& callback) {
        call_service<trt_StartMulticastStreaming, trt_StartMulticastStreamingResponse>(
            "http://www.onvif.org/ver10/media/wsdl/StartMulticastStreaming",
            request,
            "StartMulticastStreaming",
            "StartMulticastStreamingResponse",
            callback
        );
    }

    /**
     * @brief StopMulticastStreaming operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void StopMulticastStreaming(const trt_StopMulticastStreaming& request,
                           const OnvifCallback<trt_StopMulticastStreamingResponse>& callback) {
        call_service<trt_StopMulticastStreaming, trt_StopMulticastStreamingResponse>(
            "http://www.onvif.org/ver10/media/wsdl/StopMulticastStreaming",
            request,
            "StopMulticastStreaming",
            "StopMulticastStreamingResponse",
            callback
        );
    }

    /**
     * @brief SetSynchronizationPoint operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetSynchronizationPoint(const trt_SetSynchronizationPoint& request,
                           const OnvifCallback<trt_SetSynchronizationPointResponse>& callback) {
        call_service<trt_SetSynchronizationPoint, trt_SetSynchronizationPointResponse>(
            "http://www.onvif.org/ver10/media/wsdl/SetSynchronizationPoint",
            request,
            "SetSynchronizationPoint",
            "SetSynchronizationPointResponse",
            callback
        );
    }

    /**
     * @brief GetSnapshotUri operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetSnapshotUri(const trt_GetSnapshotUri& request,
                           const OnvifCallback<trt_GetSnapshotUriResponse>& callback) {
        call_service<trt_GetSnapshotUri, trt_GetSnapshotUriResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetSnapshotUri",
            request,
            "GetSnapshotUri",
            "GetSnapshotUriResponse",
            callback
        );
    }

    /**
     * @brief GetVideoSourceModes operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetVideoSourceModes(const trt_GetVideoSourceModes& request,
                           const OnvifCallback<trt_GetVideoSourceModesResponse>& callback) {
        call_service<trt_GetVideoSourceModes, trt_GetVideoSourceModesResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetVideoSourceModes",
            request,
            "GetVideoSourceModes",
            "GetVideoSourceModesResponse",
            callback
        );
    }

    /**
     * @brief SetVideoSourceMode operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetVideoSourceMode(const trt_SetVideoSourceMode& request,
                           const OnvifCallback<trt_SetVideoSourceModeResponse>& callback) {
        call_service<trt_SetVideoSourceMode, trt_SetVideoSourceModeResponse>(
            "http://www.onvif.org/ver10/media/wsdl/SetVideoSourceMode",
            request,
            "SetVideoSourceMode",
            "SetVideoSourceModeResponse",
            callback
        );
    }

    /**
     * @brief GetOSDs operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetOSDs(const trt_GetOSDs& request,
                           const OnvifCallback<trt_GetOSDsResponse>& callback) {
        call_service<trt_GetOSDs, trt_GetOSDsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetOSDs",
            request,
            "GetOSDs",
            "GetOSDsResponse",
            callback
        );
    }

    /**
     * @brief GetOSD operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetOSD(const trt_GetOSD& request,
                           const OnvifCallback<trt_GetOSDResponse>& callback) {
        call_service<trt_GetOSD, trt_GetOSDResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetOSD",
            request,
            "GetOSD",
            "GetOSDResponse",
            callback
        );
    }

    /**
     * @brief GetOSDOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetOSDOptions(const trt_GetOSDOptions& request,
                           const OnvifCallback<trt_GetOSDOptionsResponse>& callback) {
        call_service<trt_GetOSDOptions, trt_GetOSDOptionsResponse>(
            "http://www.onvif.org/ver10/media/wsdl/GetOSDOptions",
            request,
            "GetOSDOptions",
            "GetOSDOptionsResponse",
            callback
        );
    }

    /**
     * @brief SetOSD operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetOSD(const trt_SetOSD& request,
                           const OnvifCallback<trt_SetOSDResponse>& callback) {
        call_service<trt_SetOSD, trt_SetOSDResponse>(
            "http://www.onvif.org/ver10/media/wsdl/SetOSD",
            request,
            "SetOSD",
            "SetOSDResponse",
            callback
        );
    }

    /**
     * @brief CreateOSD operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateOSD(const trt_CreateOSD& request,
                           const OnvifCallback<trt_CreateOSDResponse>& callback) {
        call_service<trt_CreateOSD, trt_CreateOSDResponse>(
            "http://www.onvif.org/ver10/media/wsdl/CreateOSD",
            request,
            "CreateOSD",
            "CreateOSDResponse",
            callback
        );
    }

    /**
     * @brief DeleteOSD operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteOSD(const trt_DeleteOSD& request,
                           const OnvifCallback<trt_DeleteOSDResponse>& callback) {
        call_service<trt_DeleteOSD, trt_DeleteOSDResponse>(
            "http://www.onvif.org/ver10/media/wsdl/DeleteOSD",
            request,
            "DeleteOSD",
            "DeleteOSDResponse",
            callback
        );
    }

    const char *get_namespace_prefix() const override {
        return TARGET_NAMESPACE_PREFIX;
    }

    const char *get_namespace_uri() const override {
        return TARGET_NAMESPACE;
    }

    static constexpr const char* TARGET_NAMESPACE = "http://www.onvif.org/ver10/media/wsdl";
    static constexpr const char* TARGET_NAMESPACE_PREFIX = "trt";
};

} // namespace libonvif_client
