/**
 * @file PTZClient.h
 * @brief PTZService client (header-only)
 * @note This file is auto-generated by wsdl_parser2, do not modify manually
 */

#pragma once

#include <libonvif_client/core/onvif_service_base.h>
#include <libonvif_client/core/onvif_callback.h>
#include <libonvif_client/types/tptz.h>

namespace libonvif_client {

/**
 * @brief PTZService client
 * @namespace http://www.onvif.org/ver20/ptz/wsdl
 */
class PTZClient : public OnvifServiceBase {
public:
    /**
     * @brief Constructor
     * @param service_url ONVIF service endpoint URL
     * @param http_client HTTP client implementation (user provided)
     * @param username Authentication username (optional)
     * @param password Authentication password (optional)
     */
    PTZClient(const std::string& service_url,
                    const std::shared_ptr<IHttpClient>& http_client,
                    const std::string& username = "",
                    const std::string& password = "")
        : OnvifServiceBase(service_url, http_client, username, password) {
    }

    /**
     * @brief GetServiceCapabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetServiceCapabilities(const tptz_GetServiceCapabilities& request,
                           const OnvifCallback<tptz_GetServiceCapabilitiesResponse>& callback) {
        call_service<tptz_GetServiceCapabilities, tptz_GetServiceCapabilitiesResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GetServiceCapabilities",
            request,
            "GetServiceCapabilities",
            "GetServiceCapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief GetNodes operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetNodes(const tptz_GetNodes& request,
                           const OnvifCallback<tptz_GetNodesResponse>& callback) {
        call_service<tptz_GetNodes, tptz_GetNodesResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GetNodes",
            request,
            "GetNodes",
            "GetNodesResponse",
            callback
        );
    }

    /**
     * @brief GetNode operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetNode(const tptz_GetNode& request,
                           const OnvifCallback<tptz_GetNodeResponse>& callback) {
        call_service<tptz_GetNode, tptz_GetNodeResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GetNode",
            request,
            "GetNode",
            "GetNodeResponse",
            callback
        );
    }

    /**
     * @brief GetConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetConfiguration(const tptz_GetConfiguration& request,
                           const OnvifCallback<tptz_GetConfigurationResponse>& callback) {
        call_service<tptz_GetConfiguration, tptz_GetConfigurationResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GetConfiguration",
            request,
            "GetConfiguration",
            "GetConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetConfigurations(const tptz_GetConfigurations& request,
                           const OnvifCallback<tptz_GetConfigurationsResponse>& callback) {
        call_service<tptz_GetConfigurations, tptz_GetConfigurationsResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GetConfigurations",
            request,
            "GetConfigurations",
            "GetConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief SetConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetConfiguration(const tptz_SetConfiguration& request,
                           const OnvifCallback<tptz_SetConfigurationResponse>& callback) {
        call_service<tptz_SetConfiguration, tptz_SetConfigurationResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/SetConfiguration",
            request,
            "SetConfiguration",
            "SetConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetConfigurationOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetConfigurationOptions(const tptz_GetConfigurationOptions& request,
                           const OnvifCallback<tptz_GetConfigurationOptionsResponse>& callback) {
        call_service<tptz_GetConfigurationOptions, tptz_GetConfigurationOptionsResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GetConfigurationOptions",
            request,
            "GetConfigurationOptions",
            "GetConfigurationOptionsResponse",
            callback
        );
    }

    /**
     * @brief SendAuxiliaryCommand operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SendAuxiliaryCommand(const tptz_SendAuxiliaryCommand& request,
                           const OnvifCallback<tptz_SendAuxiliaryCommandResponse>& callback) {
        call_service<tptz_SendAuxiliaryCommand, tptz_SendAuxiliaryCommandResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/SendAuxiliaryCommand",
            request,
            "SendAuxiliaryCommand",
            "SendAuxiliaryCommandResponse",
            callback
        );
    }

    /**
     * @brief GetPresets operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetPresets(const tptz_GetPresets& request,
                           const OnvifCallback<tptz_GetPresetsResponse>& callback) {
        call_service<tptz_GetPresets, tptz_GetPresetsResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GetPresets",
            request,
            "GetPresets",
            "GetPresetsResponse",
            callback
        );
    }

    /**
     * @brief SetPreset operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetPreset(const tptz_SetPreset& request,
                           const OnvifCallback<tptz_SetPresetResponse>& callback) {
        call_service<tptz_SetPreset, tptz_SetPresetResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/SetPreset",
            request,
            "SetPreset",
            "SetPresetResponse",
            callback
        );
    }

    /**
     * @brief RemovePreset operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemovePreset(const tptz_RemovePreset& request,
                           const OnvifCallback<tptz_RemovePresetResponse>& callback) {
        call_service<tptz_RemovePreset, tptz_RemovePresetResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/RemovePreset",
            request,
            "RemovePreset",
            "RemovePresetResponse",
            callback
        );
    }

    /**
     * @brief GotoPreset operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GotoPreset(const tptz_GotoPreset& request,
                           const OnvifCallback<tptz_GotoPresetResponse>& callback) {
        call_service<tptz_GotoPreset, tptz_GotoPresetResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GotoPreset",
            request,
            "GotoPreset",
            "GotoPresetResponse",
            callback
        );
    }

    /**
     * @brief GotoHomePosition operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GotoHomePosition(const tptz_GotoHomePosition& request,
                           const OnvifCallback<tptz_GotoHomePositionResponse>& callback) {
        call_service<tptz_GotoHomePosition, tptz_GotoHomePositionResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GotoHomePosition",
            request,
            "GotoHomePosition",
            "GotoHomePositionResponse",
            callback
        );
    }

    /**
     * @brief SetHomePosition operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetHomePosition(const tptz_SetHomePosition& request,
                           const OnvifCallback<tptz_SetHomePositionResponse>& callback) {
        call_service<tptz_SetHomePosition, tptz_SetHomePositionResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/SetHomePosition",
            request,
            "SetHomePosition",
            "SetHomePositionResponse",
            callback
        );
    }

    /**
     * @brief ContinuousMove operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void ContinuousMove(const tptz_ContinuousMove& request,
                           const OnvifCallback<tptz_ContinuousMoveResponse>& callback) {
        call_service<tptz_ContinuousMove, tptz_ContinuousMoveResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/ContinuousMove",
            request,
            "ContinuousMove",
            "ContinuousMoveResponse",
            callback
        );
    }

    /**
     * @brief RelativeMove operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RelativeMove(const tptz_RelativeMove& request,
                           const OnvifCallback<tptz_RelativeMoveResponse>& callback) {
        call_service<tptz_RelativeMove, tptz_RelativeMoveResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/RelativeMove",
            request,
            "RelativeMove",
            "RelativeMoveResponse",
            callback
        );
    }

    /**
     * @brief GetStatus operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetStatus(const tptz_GetStatus& request,
                           const OnvifCallback<tptz_GetStatusResponse>& callback) {
        call_service<tptz_GetStatus, tptz_GetStatusResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GetStatus",
            request,
            "GetStatus",
            "GetStatusResponse",
            callback
        );
    }

    /**
     * @brief AbsoluteMove operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void AbsoluteMove(const tptz_AbsoluteMove& request,
                           const OnvifCallback<tptz_AbsoluteMoveResponse>& callback) {
        call_service<tptz_AbsoluteMove, tptz_AbsoluteMoveResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/AbsoluteMove",
            request,
            "AbsoluteMove",
            "AbsoluteMoveResponse",
            callback
        );
    }

    /**
     * @brief GeoMove operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GeoMove(const tptz_GeoMove& request,
                           const OnvifCallback<tptz_GeoMoveResponse>& callback) {
        call_service<tptz_GeoMove, tptz_GeoMoveResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GeoMove",
            request,
            "GeoMove",
            "GeoMoveResponse",
            callback
        );
    }

    /**
     * @brief Stop operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void Stop(const tptz_Stop& request,
                           const OnvifCallback<tptz_StopResponse>& callback) {
        call_service<tptz_Stop, tptz_StopResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/Stop",
            request,
            "Stop",
            "StopResponse",
            callback
        );
    }

    /**
     * @brief GetPresetTours operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetPresetTours(const tptz_GetPresetTours& request,
                           const OnvifCallback<tptz_GetPresetToursResponse>& callback) {
        call_service<tptz_GetPresetTours, tptz_GetPresetToursResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTours",
            request,
            "GetPresetTours",
            "GetPresetToursResponse",
            callback
        );
    }

    /**
     * @brief GetPresetTour operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetPresetTour(const tptz_GetPresetTour& request,
                           const OnvifCallback<tptz_GetPresetTourResponse>& callback) {
        call_service<tptz_GetPresetTour, tptz_GetPresetTourResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTour",
            request,
            "GetPresetTour",
            "GetPresetTourResponse",
            callback
        );
    }

    /**
     * @brief GetPresetTourOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetPresetTourOptions(const tptz_GetPresetTourOptions& request,
                           const OnvifCallback<tptz_GetPresetTourOptionsResponse>& callback) {
        call_service<tptz_GetPresetTourOptions, tptz_GetPresetTourOptionsResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GetPresetTourOptions",
            request,
            "GetPresetTourOptions",
            "GetPresetTourOptionsResponse",
            callback
        );
    }

    /**
     * @brief CreatePresetTour operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreatePresetTour(const tptz_CreatePresetTour& request,
                           const OnvifCallback<tptz_CreatePresetTourResponse>& callback) {
        call_service<tptz_CreatePresetTour, tptz_CreatePresetTourResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/CreatePresetTour",
            request,
            "CreatePresetTour",
            "CreatePresetTourResponse",
            callback
        );
    }

    /**
     * @brief ModifyPresetTour operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void ModifyPresetTour(const tptz_ModifyPresetTour& request,
                           const OnvifCallback<tptz_ModifyPresetTourResponse>& callback) {
        call_service<tptz_ModifyPresetTour, tptz_ModifyPresetTourResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/ModifyPresetTour",
            request,
            "ModifyPresetTour",
            "ModifyPresetTourResponse",
            callback
        );
    }

    /**
     * @brief OperatePresetTour operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void OperatePresetTour(const tptz_OperatePresetTour& request,
                           const OnvifCallback<tptz_OperatePresetTourResponse>& callback) {
        call_service<tptz_OperatePresetTour, tptz_OperatePresetTourResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/OperatePresetTour",
            request,
            "OperatePresetTour",
            "OperatePresetTourResponse",
            callback
        );
    }

    /**
     * @brief RemovePresetTour operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void RemovePresetTour(const tptz_RemovePresetTour& request,
                           const OnvifCallback<tptz_RemovePresetTourResponse>& callback) {
        call_service<tptz_RemovePresetTour, tptz_RemovePresetTourResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/RemovePresetTour",
            request,
            "RemovePresetTour",
            "RemovePresetTourResponse",
            callback
        );
    }

    /**
     * @brief GetCompatibleConfigurations operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetCompatibleConfigurations(const tptz_GetCompatibleConfigurations& request,
                           const OnvifCallback<tptz_GetCompatibleConfigurationsResponse>& callback) {
        call_service<tptz_GetCompatibleConfigurations, tptz_GetCompatibleConfigurationsResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/GetCompatibleConfigurations",
            request,
            "GetCompatibleConfigurations",
            "GetCompatibleConfigurationsResponse",
            callback
        );
    }

    /**
     * @brief MoveAndStartTracking operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void MoveAndStartTracking(const tptz_MoveAndStartTracking& request,
                           const OnvifCallback<tptz_MoveAndStartTrackingResponse>& callback) {
        call_service<tptz_MoveAndStartTracking, tptz_MoveAndStartTrackingResponse>(
            "http://www.onvif.org/ver20/ptz/wsdl/MoveAndStartTracking",
            request,
            "MoveAndStartTracking",
            "MoveAndStartTrackingResponse",
            callback
        );
    }

    const char *get_namespace_prefix() const override {
        return TARGET_NAMESPACE_PREFIX;
    }

    const char *get_namespace_uri() const override {
        return TARGET_NAMESPACE;
    }

    static constexpr const char* TARGET_NAMESPACE = "http://www.onvif.org/ver20/ptz/wsdl";
    static constexpr const char* TARGET_NAMESPACE_PREFIX = "tptz";
};

} // namespace libonvif_client
