/**
 * @file ReceiverPortClient.h
 * @brief ReceiverPortService client (header-only)
 * @note This file is auto-generated by wsdl_parser2, do not modify manually
 */

#pragma once

#include <libonvif_client/core/onvif_service_base.h>
#include <libonvif_client/core/onvif_callback.h>
#include <libonvif_client/types/trv.h>

namespace libonvif_client {

/**
 * @brief ReceiverPortService client
 * @namespace http://www.onvif.org/ver10/receiver/wsdl
 */
class ReceiverPortClient : public OnvifServiceBase {
public:
    /**
     * @brief Constructor
     * @param service_url ONVIF service endpoint URL
     * @param http_client HTTP client implementation (user provided)
     * @param username Authentication username (optional)
     * @param password Authentication password (optional)
     */
    ReceiverPortClient(const std::string& service_url,
                    const std::shared_ptr<IHttpClient>& http_client,
                    const std::string& username = "",
                    const std::string& password = "")
        : OnvifServiceBase(service_url, http_client, username, password) {
    }

    /**
     * @brief GetServiceCapabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetServiceCapabilities(const trv_GetServiceCapabilities& request,
                           const OnvifCallback<trv_GetServiceCapabilitiesResponse>& callback) {
        call_service<trv_GetServiceCapabilities, trv_GetServiceCapabilitiesResponse>(
            "http://www.onvif.org/ver10/receiver/wsdl/GetServiceCapabilities",
            request,
            "GetServiceCapabilities",
            "GetServiceCapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief GetReceivers operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetReceivers(const trv_GetReceivers& request,
                           const OnvifCallback<trv_GetReceiversResponse>& callback) {
        call_service<trv_GetReceivers, trv_GetReceiversResponse>(
            "http://www.onvif.org/ver10/receiver/wsdl/GetReceivers",
            request,
            "GetReceivers",
            "GetReceiversResponse",
            callback
        );
    }

    /**
     * @brief GetReceiver operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetReceiver(const trv_GetReceiver& request,
                           const OnvifCallback<trv_GetReceiverResponse>& callback) {
        call_service<trv_GetReceiver, trv_GetReceiverResponse>(
            "http://www.onvif.org/ver10/receiver/wsdl/GetReceiver",
            request,
            "GetReceiver",
            "GetReceiverResponse",
            callback
        );
    }

    /**
     * @brief CreateReceiver operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateReceiver(const trv_CreateReceiver& request,
                           const OnvifCallback<trv_CreateReceiverResponse>& callback) {
        call_service<trv_CreateReceiver, trv_CreateReceiverResponse>(
            "http://www.onvif.org/ver10/receiver/wsdl/CreateReceiver",
            request,
            "CreateReceiver",
            "CreateReceiverResponse",
            callback
        );
    }

    /**
     * @brief DeleteReceiver operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteReceiver(const trv_DeleteReceiver& request,
                           const OnvifCallback<trv_DeleteReceiverResponse>& callback) {
        call_service<trv_DeleteReceiver, trv_DeleteReceiverResponse>(
            "http://www.onvif.org/ver10/receiver/wsdl/DeleteReceiver",
            request,
            "DeleteReceiver",
            "DeleteReceiverResponse",
            callback
        );
    }

    /**
     * @brief ConfigureReceiver operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void ConfigureReceiver(const trv_ConfigureReceiver& request,
                           const OnvifCallback<trv_ConfigureReceiverResponse>& callback) {
        call_service<trv_ConfigureReceiver, trv_ConfigureReceiverResponse>(
            "http://www.onvif.org/ver10/receiver/wsdl/ConfigureReceiver",
            request,
            "ConfigureReceiver",
            "ConfigureReceiverResponse",
            callback
        );
    }

    /**
     * @brief SetReceiverMode operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetReceiverMode(const trv_SetReceiverMode& request,
                           const OnvifCallback<trv_SetReceiverModeResponse>& callback) {
        call_service<trv_SetReceiverMode, trv_SetReceiverModeResponse>(
            "http://www.onvif.org/ver10/receiver/wsdl/SetReceiverMode",
            request,
            "SetReceiverMode",
            "SetReceiverModeResponse",
            callback
        );
    }

    /**
     * @brief GetReceiverState operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetReceiverState(const trv_GetReceiverState& request,
                           const OnvifCallback<trv_GetReceiverStateResponse>& callback) {
        call_service<trv_GetReceiverState, trv_GetReceiverStateResponse>(
            "http://www.onvif.org/ver10/receiver/wsdl/GetReceiverState",
            request,
            "GetReceiverState",
            "GetReceiverStateResponse",
            callback
        );
    }

    const char *get_namespace_prefix() const override {
        return TARGET_NAMESPACE_PREFIX;
    }

    const char *get_namespace_uri() const override {
        return TARGET_NAMESPACE;
    }

    static constexpr const char* TARGET_NAMESPACE = "http://www.onvif.org/ver10/receiver/wsdl";
    static constexpr const char* TARGET_NAMESPACE_PREFIX = "trv";
};

} // namespace libonvif_client
