/**
 * @file RecordingPortClient.h
 * @brief RecordingPortService client (header-only)
 * @note This file is auto-generated by wsdl_parser2, do not modify manually
 */

#pragma once

#include <libonvif_client/core/onvif_service_base.h>
#include <libonvif_client/core/onvif_callback.h>
#include <libonvif_client/types/trc.h>

namespace libonvif_client {

/**
 * @brief RecordingPortService client
 * @namespace http://www.onvif.org/ver10/recording/wsdl
 */
class RecordingPortClient : public OnvifServiceBase {
public:
    /**
     * @brief Constructor
     * @param service_url ONVIF service endpoint URL
     * @param http_client HTTP client implementation (user provided)
     * @param username Authentication username (optional)
     * @param password Authentication password (optional)
     */
    RecordingPortClient(const std::string& service_url,
                    const std::shared_ptr<IHttpClient>& http_client,
                    const std::string& username = "",
                    const std::string& password = "")
        : OnvifServiceBase(service_url, http_client, username, password) {
    }

    /**
     * @brief GetServiceCapabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetServiceCapabilities(const trc_GetServiceCapabilities& request,
                           const OnvifCallback<trc_GetServiceCapabilitiesResponse>& callback) {
        call_service<trc_GetServiceCapabilities, trc_GetServiceCapabilitiesResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/GetServiceCapabilities",
            request,
            "GetServiceCapabilities",
            "GetServiceCapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief CreateRecording operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateRecording(const trc_CreateRecording& request,
                           const OnvifCallback<trc_CreateRecordingResponse>& callback) {
        call_service<trc_CreateRecording, trc_CreateRecordingResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/CreateRecording",
            request,
            "CreateRecording",
            "CreateRecordingResponse",
            callback
        );
    }

    /**
     * @brief DeleteRecording operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteRecording(const trc_DeleteRecording& request,
                           const OnvifCallback<trc_DeleteRecordingResponse>& callback) {
        call_service<trc_DeleteRecording, trc_DeleteRecordingResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/DeleteRecording",
            request,
            "DeleteRecording",
            "DeleteRecordingResponse",
            callback
        );
    }

    /**
     * @brief GetRecordings operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRecordings(const trc_GetRecordings& request,
                           const OnvifCallback<trc_GetRecordingsResponse>& callback) {
        call_service<trc_GetRecordings, trc_GetRecordingsResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/GetRecordings",
            request,
            "GetRecordings",
            "GetRecordingsResponse",
            callback
        );
    }

    /**
     * @brief SetRecordingConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetRecordingConfiguration(const trc_SetRecordingConfiguration& request,
                           const OnvifCallback<trc_SetRecordingConfigurationResponse>& callback) {
        call_service<trc_SetRecordingConfiguration, trc_SetRecordingConfigurationResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/SetRecordingConfiguration",
            request,
            "SetRecordingConfiguration",
            "SetRecordingConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetRecordingConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRecordingConfiguration(const trc_GetRecordingConfiguration& request,
                           const OnvifCallback<trc_GetRecordingConfigurationResponse>& callback) {
        call_service<trc_GetRecordingConfiguration, trc_GetRecordingConfigurationResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/GetRecordingConfiguration",
            request,
            "GetRecordingConfiguration",
            "GetRecordingConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetRecordingOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRecordingOptions(const trc_GetRecordingOptions& request,
                           const OnvifCallback<trc_GetRecordingOptionsResponse>& callback) {
        call_service<trc_GetRecordingOptions, trc_GetRecordingOptionsResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/GetRecordingOptions",
            request,
            "GetRecordingOptions",
            "GetRecordingOptionsResponse",
            callback
        );
    }

    /**
     * @brief CreateTrack operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateTrack(const trc_CreateTrack& request,
                           const OnvifCallback<trc_CreateTrackResponse>& callback) {
        call_service<trc_CreateTrack, trc_CreateTrackResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/CreateTrack",
            request,
            "CreateTrack",
            "CreateTrackResponse",
            callback
        );
    }

    /**
     * @brief DeleteTrack operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteTrack(const trc_DeleteTrack& request,
                           const OnvifCallback<trc_DeleteTrackResponse>& callback) {
        call_service<trc_DeleteTrack, trc_DeleteTrackResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/DeleteTrack",
            request,
            "DeleteTrack",
            "DeleteTrackResponse",
            callback
        );
    }

    /**
     * @brief GetTrackConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetTrackConfiguration(const trc_GetTrackConfiguration& request,
                           const OnvifCallback<trc_GetTrackConfigurationResponse>& callback) {
        call_service<trc_GetTrackConfiguration, trc_GetTrackConfigurationResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/GetTrackConfiguration",
            request,
            "GetTrackConfiguration",
            "GetTrackConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetTrackConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetTrackConfiguration(const trc_SetTrackConfiguration& request,
                           const OnvifCallback<trc_SetTrackConfigurationResponse>& callback) {
        call_service<trc_SetTrackConfiguration, trc_SetTrackConfigurationResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/SetTrackConfiguration",
            request,
            "SetTrackConfiguration",
            "SetTrackConfigurationResponse",
            callback
        );
    }

    /**
     * @brief CreateRecordingJob operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateRecordingJob(const trc_CreateRecordingJob& request,
                           const OnvifCallback<trc_CreateRecordingJobResponse>& callback) {
        call_service<trc_CreateRecordingJob, trc_CreateRecordingJobResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/CreateRecordingJob",
            request,
            "CreateRecordingJob",
            "CreateRecordingJobResponse",
            callback
        );
    }

    /**
     * @brief DeleteRecordingJob operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteRecordingJob(const trc_DeleteRecordingJob& request,
                           const OnvifCallback<trc_DeleteRecordingJobResponse>& callback) {
        call_service<trc_DeleteRecordingJob, trc_DeleteRecordingJobResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/DeleteRecordingJob",
            request,
            "DeleteRecordingJob",
            "DeleteRecordingJobResponse",
            callback
        );
    }

    /**
     * @brief GetRecordingJobs operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRecordingJobs(const trc_GetRecordingJobs& request,
                           const OnvifCallback<trc_GetRecordingJobsResponse>& callback) {
        call_service<trc_GetRecordingJobs, trc_GetRecordingJobsResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/GetRecordingJobs",
            request,
            "GetRecordingJobs",
            "GetRecordingJobsResponse",
            callback
        );
    }

    /**
     * @brief SetRecordingJobConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetRecordingJobConfiguration(const trc_SetRecordingJobConfiguration& request,
                           const OnvifCallback<trc_SetRecordingJobConfigurationResponse>& callback) {
        call_service<trc_SetRecordingJobConfiguration, trc_SetRecordingJobConfigurationResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/SetRecordingJobConfiguration",
            request,
            "SetRecordingJobConfiguration",
            "SetRecordingJobConfigurationResponse",
            callback
        );
    }

    /**
     * @brief GetRecordingJobConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRecordingJobConfiguration(const trc_GetRecordingJobConfiguration& request,
                           const OnvifCallback<trc_GetRecordingJobConfigurationResponse>& callback) {
        call_service<trc_GetRecordingJobConfiguration, trc_GetRecordingJobConfigurationResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/GetRecordingJobConfiguration",
            request,
            "GetRecordingJobConfiguration",
            "GetRecordingJobConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetRecordingJobMode operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetRecordingJobMode(const trc_SetRecordingJobMode& request,
                           const OnvifCallback<trc_SetRecordingJobModeResponse>& callback) {
        call_service<trc_SetRecordingJobMode, trc_SetRecordingJobModeResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/SetRecordingJobMode",
            request,
            "SetRecordingJobMode",
            "SetRecordingJobModeResponse",
            callback
        );
    }

    /**
     * @brief GetRecordingJobState operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRecordingJobState(const trc_GetRecordingJobState& request,
                           const OnvifCallback<trc_GetRecordingJobStateResponse>& callback) {
        call_service<trc_GetRecordingJobState, trc_GetRecordingJobStateResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/GetRecordingJobState",
            request,
            "GetRecordingJobState",
            "GetRecordingJobStateResponse",
            callback
        );
    }

    /**
     * @brief ExportRecordedData operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void ExportRecordedData(const trc_ExportRecordedData& request,
                           const OnvifCallback<trc_ExportRecordedDataResponse>& callback) {
        call_service<trc_ExportRecordedData, trc_ExportRecordedDataResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/ExportRecordedData",
            request,
            "ExportRecordedData",
            "ExportRecordedDataResponse",
            callback
        );
    }

    /**
     * @brief StopExportRecordedData operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void StopExportRecordedData(const trc_StopExportRecordedData& request,
                           const OnvifCallback<trc_StopExportRecordedDataResponse>& callback) {
        call_service<trc_StopExportRecordedData, trc_StopExportRecordedDataResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/StopExportRecordedData",
            request,
            "StopExportRecordedData",
            "StopExportRecordedDataResponse",
            callback
        );
    }

    /**
     * @brief GetExportRecordedDataState operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetExportRecordedDataState(const trc_GetExportRecordedDataState& request,
                           const OnvifCallback<trc_GetExportRecordedDataStateResponse>& callback) {
        call_service<trc_GetExportRecordedDataState, trc_GetExportRecordedDataStateResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/GetExportRecordedDataState",
            request,
            "GetExportRecordedDataState",
            "GetExportRecordedDataStateResponse",
            callback
        );
    }

    /**
     * @brief OverrideSegmentDuration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void OverrideSegmentDuration(const trc_OverrideSegmentDuration& request,
                           const OnvifCallback<trc_OverrideSegmentDurationResponse>& callback) {
        call_service<trc_OverrideSegmentDuration, trc_OverrideSegmentDurationResponse>(
            "http://www.onvif.org/ver10/recording/wsdl/OverrideSegmentDuration",
            request,
            "OverrideSegmentDuration",
            "OverrideSegmentDurationResponse",
            callback
        );
    }

    const char *get_namespace_prefix() const override {
        return TARGET_NAMESPACE_PREFIX;
    }

    const char *get_namespace_uri() const override {
        return TARGET_NAMESPACE;
    }

    static constexpr const char* TARGET_NAMESPACE = "http://www.onvif.org/ver10/recording/wsdl";
    static constexpr const char* TARGET_NAMESPACE_PREFIX = "trc";
};

} // namespace libonvif_client
