/**
 * @file ReplayPortClient.h
 * @brief ReplayPortService client (header-only)
 * @note This file is auto-generated by wsdl_parser2, do not modify manually
 */

#pragma once

#include <libonvif_client/core/onvif_service_base.h>
#include <libonvif_client/core/onvif_callback.h>
#include <libonvif_client/types/trp.h>

namespace libonvif_client {

/**
 * @brief ReplayPortService client
 * @namespace http://www.onvif.org/ver10/replay/wsdl
 */
class ReplayPortClient : public OnvifServiceBase {
public:
    /**
     * @brief Constructor
     * @param service_url ONVIF service endpoint URL
     * @param http_client HTTP client implementation (user provided)
     * @param username Authentication username (optional)
     * @param password Authentication password (optional)
     */
    ReplayPortClient(const std::string& service_url,
                    const std::shared_ptr<IHttpClient>& http_client,
                    const std::string& username = "",
                    const std::string& password = "")
        : OnvifServiceBase(service_url, http_client, username, password) {
    }

    /**
     * @brief GetServiceCapabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetServiceCapabilities(const trp_GetServiceCapabilities& request,
                           const OnvifCallback<trp_GetServiceCapabilitiesResponse>& callback) {
        call_service<trp_GetServiceCapabilities, trp_GetServiceCapabilitiesResponse>(
            "http://www.onvif.org/ver10/replay/wsdl/GetServiceCapabilities",
            request,
            "GetServiceCapabilities",
            "GetServiceCapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief GetReplayUri operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetReplayUri(const trp_GetReplayUri& request,
                           const OnvifCallback<trp_GetReplayUriResponse>& callback) {
        call_service<trp_GetReplayUri, trp_GetReplayUriResponse>(
            "http://www.onvif.org/ver10/replay/wsdl/GetReplayUri",
            request,
            "GetReplayUri",
            "GetReplayUriResponse",
            callback
        );
    }

    /**
     * @brief GetReplayConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetReplayConfiguration(const trp_GetReplayConfiguration& request,
                           const OnvifCallback<trp_GetReplayConfigurationResponse>& callback) {
        call_service<trp_GetReplayConfiguration, trp_GetReplayConfigurationResponse>(
            "http://www.onvif.org/ver10/replay/wsdl/GetReplayConfiguration",
            request,
            "GetReplayConfiguration",
            "GetReplayConfigurationResponse",
            callback
        );
    }

    /**
     * @brief SetReplayConfiguration operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void SetReplayConfiguration(const trp_SetReplayConfiguration& request,
                           const OnvifCallback<trp_SetReplayConfigurationResponse>& callback) {
        call_service<trp_SetReplayConfiguration, trp_SetReplayConfigurationResponse>(
            "http://www.onvif.org/ver10/replay/wsdl/SetReplayConfiguration",
            request,
            "SetReplayConfiguration",
            "SetReplayConfigurationResponse",
            callback
        );
    }

    const char *get_namespace_prefix() const override {
        return TARGET_NAMESPACE_PREFIX;
    }

    const char *get_namespace_uri() const override {
        return TARGET_NAMESPACE;
    }

    static constexpr const char* TARGET_NAMESPACE = "http://www.onvif.org/ver10/replay/wsdl";
    static constexpr const char* TARGET_NAMESPACE_PREFIX = "trp";
};

} // namespace libonvif_client
