/**
 * @file RuleEnginePortClient.h
 * @brief RuleEnginePortService client (header-only)
 * @note This file is auto-generated by wsdl_parser2, do not modify manually
 */

#pragma once

#include <libonvif_client/core/onvif_service_base.h>
#include <libonvif_client/core/onvif_callback.h>
#include <libonvif_client/types/tan.h>

namespace libonvif_client {

/**
 * @brief RuleEnginePortService client
 * @namespace http://www.onvif.org/ver20/analytics/wsdl
 */
class RuleEnginePortClient : public OnvifServiceBase {
public:
    /**
     * @brief Constructor
     * @param service_url ONVIF service endpoint URL
     * @param http_client HTTP client implementation (user provided)
     * @param username Authentication username (optional)
     * @param password Authentication password (optional)
     */
    RuleEnginePortClient(const std::string& service_url,
                    const std::shared_ptr<IHttpClient>& http_client,
                    const std::string& username = "",
                    const std::string& password = "")
        : OnvifServiceBase(service_url, http_client, username, password) {
    }

    /**
     * @brief GetSupportedRules operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetSupportedRules(const tan_GetSupportedRules& request,
                           const OnvifCallback<tan_GetSupportedRulesResponse>& callback) {
        call_service<tan_GetSupportedRules, tan_GetSupportedRulesResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/GetSupportedRules",
            request,
            "GetSupportedRules",
            "GetSupportedRulesResponse",
            callback
        );
    }

    /**
     * @brief CreateRules operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateRules(const tan_CreateRules& request,
                           const OnvifCallback<tan_CreateRulesResponse>& callback) {
        call_service<tan_CreateRules, tan_CreateRulesResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/CreateRules",
            request,
            "CreateRules",
            "CreateRulesResponse",
            callback
        );
    }

    /**
     * @brief DeleteRules operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteRules(const tan_DeleteRules& request,
                           const OnvifCallback<tan_DeleteRulesResponse>& callback) {
        call_service<tan_DeleteRules, tan_DeleteRulesResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/DeleteRules",
            request,
            "DeleteRules",
            "DeleteRulesResponse",
            callback
        );
    }

    /**
     * @brief GetRules operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRules(const tan_GetRules& request,
                           const OnvifCallback<tan_GetRulesResponse>& callback) {
        call_service<tan_GetRules, tan_GetRulesResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/GetRules",
            request,
            "GetRules",
            "GetRulesResponse",
            callback
        );
    }

    /**
     * @brief GetRuleOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRuleOptions(const tan_GetRuleOptions& request,
                           const OnvifCallback<tan_GetRuleOptionsResponse>& callback) {
        call_service<tan_GetRuleOptions, tan_GetRuleOptionsResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/GetRuleOptions",
            request,
            "GetRuleOptions",
            "GetRuleOptionsResponse",
            callback
        );
    }

    /**
     * @brief ModifyRules operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void ModifyRules(const tan_ModifyRules& request,
                           const OnvifCallback<tan_ModifyRulesResponse>& callback) {
        call_service<tan_ModifyRules, tan_ModifyRulesResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/ModifyRules",
            request,
            "ModifyRules",
            "ModifyRulesResponse",
            callback
        );
    }

    /**
     * @brief GetServiceCapabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetServiceCapabilities(const tan_GetServiceCapabilities& request,
                           const OnvifCallback<tan_GetServiceCapabilitiesResponse>& callback) {
        call_service<tan_GetServiceCapabilities, tan_GetServiceCapabilitiesResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/GetServiceCapabilities",
            request,
            "GetServiceCapabilities",
            "GetServiceCapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief GetSupportedAnalyticsModules operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetSupportedAnalyticsModules(const tan_GetSupportedAnalyticsModules& request,
                           const OnvifCallback<tan_GetSupportedAnalyticsModulesResponse>& callback) {
        call_service<tan_GetSupportedAnalyticsModules, tan_GetSupportedAnalyticsModulesResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/GetSupportedAnalyticsModules",
            request,
            "GetSupportedAnalyticsModules",
            "GetSupportedAnalyticsModulesResponse",
            callback
        );
    }

    /**
     * @brief GetAnalyticsModuleOptions operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAnalyticsModuleOptions(const tan_GetAnalyticsModuleOptions& request,
                           const OnvifCallback<tan_GetAnalyticsModuleOptionsResponse>& callback) {
        call_service<tan_GetAnalyticsModuleOptions, tan_GetAnalyticsModuleOptionsResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/GetAnalyticsModuleOptions",
            request,
            "GetAnalyticsModuleOptions",
            "GetAnalyticsModuleOptionsResponse",
            callback
        );
    }

    /**
     * @brief CreateAnalyticsModules operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void CreateAnalyticsModules(const tan_CreateAnalyticsModules& request,
                           const OnvifCallback<tan_CreateAnalyticsModulesResponse>& callback) {
        call_service<tan_CreateAnalyticsModules, tan_CreateAnalyticsModulesResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/CreateAnalyticsModules",
            request,
            "CreateAnalyticsModules",
            "CreateAnalyticsModulesResponse",
            callback
        );
    }

    /**
     * @brief DeleteAnalyticsModules operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void DeleteAnalyticsModules(const tan_DeleteAnalyticsModules& request,
                           const OnvifCallback<tan_DeleteAnalyticsModulesResponse>& callback) {
        call_service<tan_DeleteAnalyticsModules, tan_DeleteAnalyticsModulesResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/DeleteAnalyticsModules",
            request,
            "DeleteAnalyticsModules",
            "DeleteAnalyticsModulesResponse",
            callback
        );
    }

    /**
     * @brief GetAnalyticsModules operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetAnalyticsModules(const tan_GetAnalyticsModules& request,
                           const OnvifCallback<tan_GetAnalyticsModulesResponse>& callback) {
        call_service<tan_GetAnalyticsModules, tan_GetAnalyticsModulesResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/GetAnalyticsModules",
            request,
            "GetAnalyticsModules",
            "GetAnalyticsModulesResponse",
            callback
        );
    }

    /**
     * @brief ModifyAnalyticsModules operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void ModifyAnalyticsModules(const tan_ModifyAnalyticsModules& request,
                           const OnvifCallback<tan_ModifyAnalyticsModulesResponse>& callback) {
        call_service<tan_ModifyAnalyticsModules, tan_ModifyAnalyticsModulesResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/ModifyAnalyticsModules",
            request,
            "ModifyAnalyticsModules",
            "ModifyAnalyticsModulesResponse",
            callback
        );
    }

    /**
     * @brief GetSupportedMetadata operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetSupportedMetadata(const tan_GetSupportedMetadata& request,
                           const OnvifCallback<tan_GetSupportedMetadataResponse>& callback) {
        call_service<tan_GetSupportedMetadata, tan_GetSupportedMetadataResponse>(
            "http://www.onvif.org/ver20/analytics/wsdl/GetSupportedMetadata",
            request,
            "GetSupportedMetadata",
            "GetSupportedMetadataResponse",
            callback
        );
    }

    const char *get_namespace_prefix() const override {
        return TARGET_NAMESPACE_PREFIX;
    }

    const char *get_namespace_uri() const override {
        return TARGET_NAMESPACE;
    }

    static constexpr const char* TARGET_NAMESPACE = "http://www.onvif.org/ver20/analytics/wsdl";
    static constexpr const char* TARGET_NAMESPACE_PREFIX = "tan";
};

} // namespace libonvif_client
