/**
 * @file SearchPortClient.h
 * @brief SearchPortService client (header-only)
 * @note This file is auto-generated by wsdl_parser2, do not modify manually
 */

#pragma once

#include <libonvif_client/core/onvif_service_base.h>
#include <libonvif_client/core/onvif_callback.h>
#include <libonvif_client/types/tse.h>

namespace libonvif_client {

/**
 * @brief SearchPortService client
 * @namespace http://www.onvif.org/ver10/search/wsdl
 */
class SearchPortClient : public OnvifServiceBase {
public:
    /**
     * @brief Constructor
     * @param service_url ONVIF service endpoint URL
     * @param http_client HTTP client implementation (user provided)
     * @param username Authentication username (optional)
     * @param password Authentication password (optional)
     */
    SearchPortClient(const std::string& service_url,
                    const std::shared_ptr<IHttpClient>& http_client,
                    const std::string& username = "",
                    const std::string& password = "")
        : OnvifServiceBase(service_url, http_client, username, password) {
    }

    /**
     * @brief GetServiceCapabilities operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetServiceCapabilities(const tse_GetServiceCapabilities& request,
                           const OnvifCallback<tse_GetServiceCapabilitiesResponse>& callback) {
        call_service<tse_GetServiceCapabilities, tse_GetServiceCapabilitiesResponse>(
            "http://www.onvif.org/ver10/search/wsdl/GetServiceCapabilities",
            request,
            "GetServiceCapabilities",
            "GetServiceCapabilitiesResponse",
            callback
        );
    }

    /**
     * @brief GetRecordingSummary operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRecordingSummary(const tse_GetRecordingSummary& request,
                           const OnvifCallback<tse_GetRecordingSummaryResponse>& callback) {
        call_service<tse_GetRecordingSummary, tse_GetRecordingSummaryResponse>(
            "http://www.onvif.org/ver10/search/wsdl/GetRecordingSummary",
            request,
            "GetRecordingSummary",
            "GetRecordingSummaryResponse",
            callback
        );
    }

    /**
     * @brief GetRecordingInformation operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRecordingInformation(const tse_GetRecordingInformation& request,
                           const OnvifCallback<tse_GetRecordingInformationResponse>& callback) {
        call_service<tse_GetRecordingInformation, tse_GetRecordingInformationResponse>(
            "http://www.onvif.org/ver10/search/wsdl/GetRecordingInformation",
            request,
            "GetRecordingInformation",
            "GetRecordingInformationResponse",
            callback
        );
    }

    /**
     * @brief GetMediaAttributes operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetMediaAttributes(const tse_GetMediaAttributes& request,
                           const OnvifCallback<tse_GetMediaAttributesResponse>& callback) {
        call_service<tse_GetMediaAttributes, tse_GetMediaAttributesResponse>(
            "http://www.onvif.org/ver10/search/wsdl/GetMediaAttributes",
            request,
            "GetMediaAttributes",
            "GetMediaAttributesResponse",
            callback
        );
    }

    /**
     * @brief FindRecordings operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void FindRecordings(const tse_FindRecordings& request,
                           const OnvifCallback<tse_FindRecordingsResponse>& callback) {
        call_service<tse_FindRecordings, tse_FindRecordingsResponse>(
            "http://www.onvif.org/ver10/search/wsdl/FindRecordings",
            request,
            "FindRecordings",
            "FindRecordingsResponse",
            callback
        );
    }

    /**
     * @brief GetRecordingSearchResults operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetRecordingSearchResults(const tse_GetRecordingSearchResults& request,
                           const OnvifCallback<tse_GetRecordingSearchResultsResponse>& callback) {
        call_service<tse_GetRecordingSearchResults, tse_GetRecordingSearchResultsResponse>(
            "http://www.onvif.org/ver10/search/wsdl/GetRecordingSearchResults",
            request,
            "GetRecordingSearchResults",
            "GetRecordingSearchResultsResponse",
            callback
        );
    }

    /**
     * @brief FindEvents operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void FindEvents(const tse_FindEvents& request,
                           const OnvifCallback<tse_FindEventsResponse>& callback) {
        call_service<tse_FindEvents, tse_FindEventsResponse>(
            "http://www.onvif.org/ver10/search/wsdl/FindEvents",
            request,
            "FindEvents",
            "FindEventsResponse",
            callback
        );
    }

    /**
     * @brief GetEventSearchResults operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetEventSearchResults(const tse_GetEventSearchResults& request,
                           const OnvifCallback<tse_GetEventSearchResultsResponse>& callback) {
        call_service<tse_GetEventSearchResults, tse_GetEventSearchResultsResponse>(
            "http://www.onvif.org/ver10/search/wsdl/GetEventSearchResults",
            request,
            "GetEventSearchResults",
            "GetEventSearchResultsResponse",
            callback
        );
    }

    /**
     * @brief FindPTZPosition operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void FindPTZPosition(const tse_FindPTZPosition& request,
                           const OnvifCallback<tse_FindPTZPositionResponse>& callback) {
        call_service<tse_FindPTZPosition, tse_FindPTZPositionResponse>(
            "http://www.onvif.org/ver10/search/wsdl/FindPTZPosition",
            request,
            "FindPTZPosition",
            "FindPTZPositionResponse",
            callback
        );
    }

    /**
     * @brief GetPTZPositionSearchResults operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetPTZPositionSearchResults(const tse_GetPTZPositionSearchResults& request,
                           const OnvifCallback<tse_GetPTZPositionSearchResultsResponse>& callback) {
        call_service<tse_GetPTZPositionSearchResults, tse_GetPTZPositionSearchResultsResponse>(
            "http://www.onvif.org/ver10/search/wsdl/GetPTZPositionSearchResults",
            request,
            "GetPTZPositionSearchResults",
            "GetPTZPositionSearchResultsResponse",
            callback
        );
    }

    /**
     * @brief GetSearchState operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetSearchState(const tse_GetSearchState& request,
                           const OnvifCallback<tse_GetSearchStateResponse>& callback) {
        call_service<tse_GetSearchState, tse_GetSearchStateResponse>(
            "http://www.onvif.org/ver10/search/wsdl/GetSearchState",
            request,
            "GetSearchState",
            "GetSearchStateResponse",
            callback
        );
    }

    /**
     * @brief EndSearch operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void EndSearch(const tse_EndSearch& request,
                           const OnvifCallback<tse_EndSearchResponse>& callback) {
        call_service<tse_EndSearch, tse_EndSearchResponse>(
            "http://www.onvif.org/ver10/search/wsdl/EndSearch",
            request,
            "EndSearch",
            "EndSearchResponse",
            callback
        );
    }

    /**
     * @brief FindMetadata operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void FindMetadata(const tse_FindMetadata& request,
                           const OnvifCallback<tse_FindMetadataResponse>& callback) {
        call_service<tse_FindMetadata, tse_FindMetadataResponse>(
            "http://www.onvif.org/ver10/search/wsdl/FindMetadata",
            request,
            "FindMetadata",
            "FindMetadataResponse",
            callback
        );
    }

    /**
     * @brief GetMetadataSearchResults operation
     * @param request Request parameters
     * @param callback Result callback
     */
    void GetMetadataSearchResults(const tse_GetMetadataSearchResults& request,
                           const OnvifCallback<tse_GetMetadataSearchResultsResponse>& callback) {
        call_service<tse_GetMetadataSearchResults, tse_GetMetadataSearchResultsResponse>(
            "http://www.onvif.org/ver10/search/wsdl/GetMetadataSearchResults",
            request,
            "GetMetadataSearchResults",
            "GetMetadataSearchResultsResponse",
            callback
        );
    }

    const char *get_namespace_prefix() const override {
        return TARGET_NAMESPACE_PREFIX;
    }

    const char *get_namespace_uri() const override {
        return TARGET_NAMESPACE;
    }

    static constexpr const char* TARGET_NAMESPACE = "http://www.onvif.org/ver10/search/wsdl";
    static constexpr const char* TARGET_NAMESPACE_PREFIX = "tse";
};

} // namespace libonvif_client
